### PR TITLE
Remove mention of atlas (which is no longer an installed model)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
https://github.com/RobotLocomotion/drake/pull/19160

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/267)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@sherm1 for both reviews, please.  High priority.

**Review by sherm1 — APPROVED** [review]
:lgtm: x 2

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/267#-:-NSqcxVGACbaN1B6FKQ-:b4xzgsb)* status: :shipit: complete! all discussions resolved, platform LGTM from [sherm1] (waiting on @jwnimmer-tri)

**Comment by sherm1** [comment]
Apparently I'm not authorized to push to this repo so I can't merge. Please add me if you can.

**Comment by jwnimmer-tri** [comment]
As best I can tell, you _are_ a `Writer` on this repo.

**Pull request merged**
