### PR TITLE
Move GHA ubuntu setup to related example subdirs

### PR DESCRIPTION
**Pull request by nicolecheetham**
Creates duplicates of the GHA ubuntu setup and distributes them to the drake examples which use it.

Issue: https://github.com/RobotLocomotion/drake-external-examples/issues/309

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/317)

### CODE REVIEW

**Review by nicolecheetham — COMMENTED** [review]
+@BetsyMcPhail for feature review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/317#-:-O7iWQosDZ2Pwdw88mc4:b-1dud86)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/317#-:-O7iZ0d3B2vkfQ3PwD9Y:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
+@sammy-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/317#-:-O7i_frm4ESqb5kZV_d4:b-6xrt9v)* status: all discussions resolved, LGTM missing from assignee sammy-tri, platform LGTM from [betsymcphail] (waiting on @sammy-tri)

**Review by sammy-tri — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/317)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

___
*[`drake_bazel_download/.github/ubuntu_setup` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/317#-O7kDlE20G6kxNCDHw7r:-O7kDlE20G6kxNCDHw7s:blzsokg) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/015a4f54e74cd8052dd010055153dee5ce8e502a/drake_bazel_download/.github/ubuntu_setup#L1)):*
> ```
> #!/bin/bash
> ```

Based on #307, I think these files need to be added to `private/file_sync_test.py`

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/317)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri, platform LGTM from [betsymcphail] (waiting on @nicolecheetham and @sammy-tri)

**Review by sammy-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/317)* status: all discussions resolved, LGTM missing from assignee sammy-tri, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

**Review by sammy-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/317#-:-O898Uga9_2nK6GzdTVp:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, sammy-tri] (waiting on @nicolecheetham)

**Pull request merged**
