### PR TITLE
[ci] Install missing macOS GHA pip3.11

### PR DESCRIPTION
**Pull request by svenevs**
Continuation of the saga: #250, #252, #257, #259.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/262)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
:lgtm: who knows how long it'll work this time, my assumption is it will break again and we'll put another bandaid on.  There doesn't seem to be any holistically resilient answer.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/262#-:-NOPwY9u8YIL5XNXAfTa:b-i6q4tk)* status: all discussions resolved, platform LGTM missing (waiting on @svenevs)

___
*[`.github/workflows/ci.yml` line 68 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/262#-NOPwUQC0FhQLYN8fEhD:-NOPwUQC0FhQLYN8fEhE:bot0ui3) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/aeb3f1974badc1932389bf84b5d9e3cda3804d91/.github/workflows/ci.yml#L68)):*
> ```YAML
>           # On 2023-02-16 the pip3.11 symlink was mysteriously missing.
>           brew unlink python@3.11 && brew link python@3.11
>           pip3.11 --version
> ```

FYI from the build log:

```
Unlinking /usr/local/Cellar/python@3.11/3.11.1... 5 symlinks removed.
Linking /usr/local/Cellar/python@3.11/3.11.1... 11 symlinks created.
```

No idea why `5` were there originally, theoretically the previous steps should have been removing the symlinks in the first place?

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/262)* status: all discussions resolved, platform LGTM missing (waiting on @svenevs)

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/262#-:-NOQ1PbKCFd7lt1CgYyZ:bnfp4nl)* status: all discussions resolved, platform LGTM missing (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
+@sammy-tri for platform review, per schedule please.  TLDR yet another bandaid, it works for now so we'd like to merge it.  Another bandaid will likely need to be applied in the future AKA we don't have a "proper" fix for this and haven't for weeks.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/262#-:-NOQ5-8PCMRbawc95-T5:bw0w4x5)* status: all discussions resolved, LGTM missing from assignee sammy-tri, platform LGTM missing (waiting on @sammy-tri)

**Review by sammy-tri — APPROVED** [review]
:lgtm: (rubber stamp for trust in the authors rather than understanding exactly whats going on here)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/262#-:-NOR2Lf37oEZnhCpIUP2:bro5on1)* status: :shipit: complete! all discussions resolved, platform LGTM from [sammy-tri] (waiting on @svenevs)

**Pull request merged**
