### PR TITLE
Add file_sync_test and start to re-home common files

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The idea here is that users should always be able to copy _just one subdirectory_ and end up with everything they need.  To the extent that we have important files outside of the `drake_...` subdirectories, the examples will be broken.

Of course that often will mean duplicating content across the sub-directories, which leads to a maintenance hazard.  We can solve that by using this new test program to cross-check that the copies are in sync.

This just moves one file as a starter pack, to bootstrap the idea.  Over time, we should make further adjustments and copies so that everything inside the `drake_...` subdirs is 100% standalone.

For now, maintainers will need to run this by hand.  Soon we plan to have #308 to add it to CI.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@BetsyMcPhail for feature review or delegation, please.

**Review by BetsyMcPhail — APPROVED** [review]
Testing locally on my system, I confirmed that changing a .clang-format file results in an error message.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307#-:-O7AbA7gDPgsNfB4ZiAx:b45anya)* status: 1 unresolved discussion, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[`private/test/file_sync_test.py` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307#-O7AauU0CyUiDt3BkXd8:-O7AauU1DntT6bP97gdh:b-nxmjgn) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/2ce847a2648c925b19fb7391fc7a2beb440ab43b/private/test/file_sync_test.py#L37)):*
> ```Python
>     # For readability, enforce that the lists are sorted.
>     first_name = Path(paths[0]).name
>     prologue = f"The {index+1}th list of files (containing {first_name})"
> ```

Nit: As there is only one file copied, this results in the error message "ERROR: The 1th list of files (containing .clang-format) do not all match"

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307#-:-O7AbMh1DF85qqhR3ys9:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [betsymcphail] (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307#-:-O7AbbrADsV3Cq0xZ8Jb:b-syrr9x)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM from [betsymcphail] (waiting on @rpoyner-tri)

___
*[`private/test/file_sync_test.py` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307#-O7AauU0CyUiDt3BkXd8:-O7Abea-BjHnD-Pnu1d5:b-gxoetg) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/2ce847a2648c925b19fb7391fc7a2beb440ab43b/private/test/file_sync_test.py#L37)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Nit: As there is only one file copied, this results in the error message "ERROR: The 1th list of files (containing .clang-format) do not all match"
</blockquote></details>

Right.  In the future we will have many more groups of copied files, and I don't know of a good way to have the f-string use proper grammar easily.

**Review by BetsyMcPhail — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM from [betsymcphail] (waiting on @rpoyner-tri)

___
*[`private/test/file_sync_test.py` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307#-O7AauU0CyUiDt3BkXd8:-O7AbyNz-wFLpWl0qjK6:b-hphvap) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/2ce847a2648c925b19fb7391fc7a2beb440ab43b/private/test/file_sync_test.py#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Right.  In the future we will have many more groups of copied files, and I don't know of a good way to have the f-string use proper grammar easily.
</blockquote></details>

Works for me, the important part is the failure.

**Review by rpoyner-tri — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM from [betsymcphail] (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307#-:-O7GaebNA0yL3w69KOwv:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/307#-O7Gaud65CimuEdDeqBH:-O7Gaud75Q_rKPNjP3qG:b-b9ncd3) (no related file):*
Huh. Merge button is there for me, but doesn't work.

___

**Pull request merged**
