### PR TITLE
Use the source version of drake's install_prereqs for external examples

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #61 

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@nicolecheetham for review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313#-:-OBbl0EcDJ1e0WWwnDhE:b31q5jk)* status: all discussions resolved, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
The Jenkins job can't find the ubuntu install_prereqs file. Everything else looks good

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313#-:-OBfBZk97UBgQzgHRZDl:bopnn6s)* status: all discussions resolved, LGTM missing from assignee nicolecheetham, platform LGTM missing

**Review by BetsyMcPhail — COMMENTED** [review]
Something must have been lost in the rebase! I will fix it.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313#-:-OBfCzmiBr_54fW4n1sP:b-3cftpi)* status: all discussions resolved, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

**Review by BetsyMcPhail — COMMENTED** [review]
@nicolecheetham this is ready for another look. I used the relevant changes from your PR  #333.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313#-:-OBgeWCb3uVqADHbf27l:b-o1fuw0)* status: 1 unresolved discussion, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

___
*[`drake_bazel_external/.github/setup` line 9 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313#-OBggDea0CfqrPMKOB7d:-OBggDea0CfqrPMKOB7e:b-17vihe) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/a320c09fbd66a7e35d855918bf55019aaf734398/drake_bazel_external/.github/setup#L9)):*
> ```
> sudo ./.github/ubuntu_setup
> 
> # Download the drake source
> ```


Some background, in both the CMake and Bazel cases, the following needs to happen for setup:

1. CI-only setup as sudo (`.github/ubuntu_setup`)
2. Get drake source NOT as sudo, in a location that can written to as the normal user AND, for the bazel example, NOT in a subdirectory to the current example (e.g. `drake_bazel_external/<not here>`)
3. Run the install script from 2 as sudo

I've removed `setup/install_prereqs` script, placed the code here and copied it in the READMEs. To avoid duplication, I could move this chunk of code to `setup/install_prereqs`, but I'm not sure where the best place to install drake source?

**Review by nicolecheetham — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313)* status: 1 unresolved discussion, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @BetsyMcPhail)

___
*[`drake_bazel_external/.github/setup` line 9 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313#-OBggDea0CfqrPMKOB7d:-OBkOISSDq9biqsklspR:bdwxd1x) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/a320c09fbd66a7e35d855918bf55019aaf734398/drake_bazel_external/.github/setup#L9)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Some background, in both the CMake and Bazel cases, the following needs to happen for setup:

1. CI-only setup as sudo (`.github/ubuntu_setup`)
2. Get drake source NOT as sudo, in a location that can written to as the normal user AND, for the bazel example, NOT in a subdirectory to the current example (e.g. `drake_bazel_external/<not here>`)
3. Run the install script from 2 as sudo

I've removed `setup/install_prereqs` script, placed the code here and copied it in the READMEs. To avoid duplication, I could move this chunk of code to `setup/install_prereqs`, but I'm not sure where the best place to install drake source?
</blockquote></details>

I agree with moving the download and installation to `setup/install_prereqs`. It would also keep the README instructions simple. And if installing the drake source can't be done in a subdirectory why don't you tell people to put it right next to the specific example directory? This way it will be close by.

**Review by BetsyMcPhail — COMMENTED** [review]
@nicolecheetham this is ready for another look please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313#-:-OCZNNkD60r3qvvhuEV-:b-6vho2i)* status: 1 unresolved discussion, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

**Review by nicolecheetham — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313#-:-OCZSVU9AXbJ3cRKWnI1:bnfp4nl)* status: 1 unresolved discussion, platform LGTM missing (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
+@xuchenhan-tri for platform review please. Note that the Mac failure is a known CI issue and that neither of the examples updated here are tested on Mac.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313#-:-OCZeaLK0iUjvxHDsQhj:ba6wrvg)* status: all discussions resolved, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @nicolecheetham and @xuchenhan-tri)

**Review by xuchenhan-tri — APPROVED** [review]
:lgtm: nice!

> Reviewed 6 of 15 files at r2, 1 of 13 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/313#-:-OCZr1UnCW1Rjs3YW-nG:b-7yytuz)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [xuchenhan-tri] (waiting on @BetsyMcPhail)

**Pull request merged**
