### PR TITLE
doc: Fix instructions for depending on local drake tree

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/197)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
+@ericcousineau-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/197#-:-MTqDQr57j_odokU37ra:b-7eskas)* status: all discussions resolved, LGTM missing from assignee ericcousineau-tri, platform LGTM missing (waiting on @EricCousineau-TRI)

**Review by rpoyner-tri — COMMENTED** [review]
The existing instructions didn't work because the very last step had a typo causing the external project to point to installed /opt/drake (which I didn't have) rather than the developer copy.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/197#-:-MTqDZlX0xhC9KuULTG_:b9akv5p)* status: all discussions resolved, LGTM missing from assignee ericcousineau-tri, platform LGTM missing (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/197#-:-MTqFJOnBl_VVIF_wF_j:bnfp4nl)* status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri] (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/197#-:-MTqFKxA0Z2ZD9PPhSGJ:b-ucfknh)* status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri] (waiting on @EricCousineau-TRI)

**Pull request merged**
