### PR TITLE
[drake_bazel_download] Port to bzlmod

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Requires:
- [x] RobotLocomotion/drake#21092

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/286)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 18 of 18 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/286)* status: 1 unresolved discussion, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[`drake_bazel_download/MODULE.bazel` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/286#-NsFN0bD3OXIsfQgL7Kl:-NsFN0bD3OXIsfQgL7Km:b-768eq9) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/d1860aebe283172c2f1eb47e526cabc2da4251ce/drake_bazel_download/MODULE.bazel#L26)):*
> ```Starlark
>         # this to a specific release version, instead. To find those URLs,
>         # refer to https://github.com/RobotLocomotion/drake/releases.
>         "https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-jammy.tar.gz"
> ```

Working

For now this is pinned to "continuous" in order to pass the tests using the recent Drake fix.  One that fix makes it into tonight's nightlies, I'll drop the second commit so that we're back to using "nightly" here.

**Review by rpoyner-tri — APPROVED** [review]
:lgtm: pending CI shuffling

> Reviewed 12 of 18 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/286#-:-NsFiIlGAxwSoVCIdec-:b-sgvlrg)* status: 1 unresolved discussion, platform LGTM from [rpoyner-tri] (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+@xuchenhan-tri for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/286#-:-NsG-kq-C3BR0gX4Owj3:bfqkacy)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri, platform LGTM from [rpoyner-tri] (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[`drake_bazel_download/MODULE.bazel` line 26 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/286#-NsFN0bD3OXIsfQgL7Kl:-NsG-neU5AheAgbvZqg8:btolfgp) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/d1860aebe283172c2f1eb47e526cabc2da4251ce/drake_bazel_download/MODULE.bazel#L26)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

For now this is pinned to "continuous" in order to pass the tests using the recent Drake fix.  One that fix makes it into tonight's nightlies, I'll drop the second commit so that we're back to using "nightly" here.
</blockquote></details>

Possibly "tonight" will not be clear for posterity: I expect the 2024-03-06 nightly to have the fix, so after those are published I'll revert this line.

**Review by rpoyner-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/286)* status: all discussions resolved, LGTM missing from assignee xuchenhan-tri, platform LGTM from [rpoyner-tri] (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — APPROVED** [review]
:lgtm:

Question: what's the goal of porting to Bzlmod? Is it for education purposes -- i.e. to show people how to use Drake as an external dependency using Bzlmod?

> Reviewed 12 of 18 files at r1, 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/286#-:-NsK8lhwBDTlN1Rru3M0:b-b13d9y)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [rpoyner-tri, xuchenhan-tri] (waiting on @jwnimmer-tri)

**Comment by xuchenhan-tri** [comment]
Good to know, thank you.

**Pull request merged**
