### PR TITLE
[ci] Hotfix macOS python packaging module missing

### PR DESCRIPTION
**Pull request by svenevs**
Bypass pyzmq setup installation errors unrelated to drake.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail for feature review please.  https://github.com/RobotLocomotion/drake-external-examples/actions/runs/3905542063/jobs/6672663128 already passed `setup` so I expect CI to pass here.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254#-:-NLbaHJF2YKwpXpYvMyP:b-p8ntto)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254#-:-NLbfltS7Mn1Gv469x3i:bnfp4nl)* status: all discussions resolved, platform LGTM missing (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
+@EricCousineau-TRI for fly-by platform stamp please :slightly_smiling_face:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254#-:-NLbgKVZE8RPuWdapnMy:b9j8e6b)* status: all discussions resolved, LGTM missing from assignee ericcousineau-tri, platform LGTM missing (waiting on @EricCousineau-TRI)

**Review by EricCousineau-TRI — APPROVED** [review]
:fly: :lgtm: platform!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254#-:-NLbwW05A7ufxaPsF00O:b-s47x42)* status: 1 unresolved discussion, platform LGTM from [ericcousineau-tri] (waiting on @svenevs)

___
*[`.github/workflows/ci.yml` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254#-NLbwn8s44-D3Xxxco8P:-NLbwn8s44-D3Xxxco8Q:bskb8rl) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/ef97f46c13ef9532a48f2b9935259d6800b738ba/.github/workflows/ci.yml#L87)):*
> ```YAML
>           brew upgrade python@3.11
>       # TODO(svenevs): On 2023-01-12 there were build failures stemming from an
>       # inability to install pyzmq due to missing packaging module.  This is
> ```

BTW Unclear if root cause is specific to PyPI or Homebrew - worth mentioning if you know, or even worth mentioning if it's not clear?

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254)* status: 1 unresolved discussion, platform LGTM from [ericcousineau-tri] (waiting on @EricCousineau-TRI)

___
*[`.github/workflows/ci.yml` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254#-NLbwn8s44-D3Xxxco8P:-NLeOWco7KBfFgj3Pwrn:brrsdn4) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/ef97f46c13ef9532a48f2b9935259d6800b738ba/.github/workflows/ci.yml#L87)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Unclear if root cause is specific to PyPI or Homebrew - worth mentioning if you know, or even worth mentioning if it's not clear?
</blockquote></details>

Good call, rephrased to be more explicit about the exact-cause-unknown.  From a brief look [pyzmq is doing the right thing](https://github.com/zeromq/pyzmq/blob/3e7e83a841829fcb46b7e1a881d968fb5471ef62/pyproject.toml#L22), so it _could_ be a regression in `pip`?  It will be worth retrying after a new `pyzmq` release, since 25.0.0 was released recently and that seems like too much of a coincidence.

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254)* status: 1 unresolved discussion, platform LGTM from [ericcousineau-tri] (waiting on @svenevs)

___
*[`.github/workflows/ci.yml` line 87 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254#-NLbwn8s44-D3Xxxco8P:-NLfVYKf76cxKkRxxhCj:b-ieyay5) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/ef97f46c13ef9532a48f2b9935259d6800b738ba/.github/workflows/ci.yml#L87)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Good call, rephrased to be more explicit about the exact-cause-unknown.  From a brief look [pyzmq is doing the right thing](https://github.com/zeromq/pyzmq/blob/3e7e83a841829fcb46b7e1a881d968fb5471ef62/pyproject.toml#L22), so it _could_ be a regression in `pip`?  It will be worth retrying after a new `pyzmq` release, since 25.0.0 was released recently and that seems like too much of a coincidence.
</blockquote></details>

OK Sweet, thanks!

**Comment by EricCousineau-TRI** [comment]
Closing / reopening to retrigger CI

**Review by EricCousineau-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254)* status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri] (waiting on @svenevs)

**Review by BetsyMcPhail — COMMENTED** [review]
We're back to passing without this PR? I saw it green and assumed this had been merged in. Should we just close this PR @svenevs?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/254#-:-NLggH06CmEfZTRCSCPt:bkf22co)* status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri] (waiting on @svenevs)

**Comment by svenevs** [comment]
Works for me :partying_face:

**Pull request closed without merging**
