### PR TITLE
Refactor Jenkins setup workflow

### PR DESCRIPTION
**Pull request by nicolecheetham**
Cleanup Jenkins setup workflow to make it more clear and concise

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301)

### CODE REVIEW

**Review by BetsyMcPhail — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301)* status: 2 unresolved discussions, platform LGTM missing (waiting on @nicolecheetham)

___
*[`scripts/continuous_integration/jenkins/setup` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301#-O6g5S2t2dfHtIq3s25g:-O6g5S2t2dfHtIq3s25h:btm40bd) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/fe4ceb8037327578cb33f39847a37f591dd52ed9/scripts/continuous_integration/jenkins/setup#L6)):*
> ```
> set -euxo pipefail
> 
> echo "WORKSPACE is: ${WORKSPACE}"
> ```

BTW Was this intended to be part of this PR?
___
*[`scripts/setup/linux/ubuntu/jammy/install_prereqs` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301#-O6g5_ZDCpQy_0LGwCqm:-O6g5_ZDCpQy_0LGwCqn:b-9i2mot) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/fe4ceb8037327578cb33f39847a37f591dd52ed9/scripts/setup/linux/ubuntu/jammy/install_prereqs#L39)):*
> ```
> export DEBIAN_FRONTEND='noninteractive'
> 
> ros_humble=0
> ```

I believe this `install_prereqs` script gets called from 3 places: 
1. scripts/continuous_integration/github_actions/ubuntu_jammy/setup
2. scripts/continuous_integration/jenkins/setup
3. scripts/continuous_integration/common/ros_humble

1. and 2. through scripts/continuous_integration/common/linux_ubuntu_jammy

In the other 2 cases, these lines are now executed twice.  Would it be more clear to move these lines to `scripts/continuous_integration/jenkins/setup`?

**Review by BetsyMcPhail — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301)* status: 2 unresolved discussions, platform LGTM missing (waiting on @nicolecheetham)

___
*[`scripts/setup/linux/ubuntu/jammy/install_prereqs` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301#-O6g5_ZDCpQy_0LGwCqm:-O6g9anzDOaT3sNWmX0e:be1w40c) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/fe4ceb8037327578cb33f39847a37f591dd52ed9/scripts/setup/linux/ubuntu/jammy/install_prereqs#L39)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I believe this `install_prereqs` script gets called from 3 places: 
1. scripts/continuous_integration/github_actions/ubuntu_jammy/setup
2. scripts/continuous_integration/jenkins/setup
3. scripts/continuous_integration/common/ros_humble

1. and 2. through scripts/continuous_integration/common/linux_ubuntu_jammy

In the other 2 cases, these lines are now executed twice.  Would it be more clear to move these lines to `scripts/continuous_integration/jenkins/setup`?
</blockquote></details>

1* and 2. through

**Review by nicolecheetham — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301)* status: 2 unresolved discussions, platform LGTM missing (waiting on @BetsyMcPhail)

___
*[`scripts/continuous_integration/jenkins/setup` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301#-O6g5S2t2dfHtIq3s25g:-O6gHQQxClt4yW4J5DfK:b-n6xosx) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/fe4ceb8037327578cb33f39847a37f591dd52ed9/scripts/continuous_integration/jenkins/setup#L6)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

BTW Was this intended to be part of this PR?
</blockquote></details>

Sorry for the miscommunication. This PR is still in the works. Currently I've been trying to reduce the complexity of calling the jammy install_prereqs through the Jenkins setup workflow. However, I have gotten an the error: unbound variable WORKSPACE when I moved the code into the jammy install_prereqs.This error was present on PR #298 and I'm trying to solve it via this PR

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301)* status: 2 unresolved discussions, platform LGTM missing (waiting on @nicolecheetham)

___
*[`scripts/continuous_integration/jenkins/setup` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301#-O6g5S2t2dfHtIq3s25g:-O6gMybC4YvgTHEvSbgu:b-5d8pds) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/fe4ceb8037327578cb33f39847a37f591dd52ed9/scripts/continuous_integration/jenkins/setup#L6)):*
<details><summary><i>Previously, nicolecheetham (Nicole C.) wrote…</i></summary><blockquote>

Sorry for the miscommunication. This PR is still in the works. Currently I've been trying to reduce the complexity of calling the jammy install_prereqs through the Jenkins setup workflow. However, I have gotten an the error: unbound variable WORKSPACE when I moved the code into the jammy install_prereqs.This error was present on PR #298 and I'm trying to solve it via this PR
</blockquote></details>

Ok! Ignore me for now and let me know when you're ready for a review

**Review by nicolecheetham — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301)* status: 2 unresolved discussions, platform LGTM missing (waiting on @BetsyMcPhail)

___
*[`scripts/setup/linux/ubuntu/jammy/install_prereqs` line 39 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/301#-O6g5_ZDCpQy_0LGwCqm:-O6gItTA9TOYgXB7vvEg:bt4v2jy) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/fe4ceb8037327578cb33f39847a37f591dd52ed9/scripts/setup/linux/ubuntu/jammy/install_prereqs#L39)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

1* and 2. through
</blockquote></details>

I can do this though I might change it depending on how the refactoring goes. This arose from me moving over only a part of the changes I made in PR 298 but thinking other changes of the PR still applied. Within 298 I had already removed the files 1, 3, and 4. Therefore, when placing this code in the install_prereqs there wouldn't be any duplication (unless I'm misremembering)

**Comment by BetsyMcPhail** [comment]
Replaced by #304

**Pull request closed without merging**
