### PR TITLE
Make examples folders self-contained by including necessary setup files

### PR DESCRIPTION
**Pull request by alesgenova**
Working towards #61

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/225)

### CODE REVIEW

**Review by BetsyMcPhail — CHANGES_REQUESTED** [review]
> Reviewed 45 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/225)* status: 2 unresolved discussions, platform LGTM missing (waiting on @alesgenova)

___
*[.github/workflows/ci.yml, line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/225#-MzLPM9i1ru1JJd1lStA:-MzLPM9i1ru1JJd1lStB:b-wxiicv) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/0e07970a25c1a9279aca6fbfa5f5a05acee0963b/.github/workflows/ci.yml#L93)):*
> ```YAML
>         run: ./scripts/continuous_integration/github_actions/ubuntu_apt/build_test
>         shell: bash
>   verify_setup_files:
> ```

This test shows as passing when it was run on this PR but it is actually failing with `git: command not found`
___
*[scripts/setup/utils/update_setup_files.sh, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/225#-MzLTKXe8rdpQ3KPgN4e:-MzLTKXe8rdpQ3KPgN4f:b-5e5t24) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/0e07970a25c1a9279aca6fbfa5f5a05acee0963b/scripts/setup/utils/update_setup_files.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

Would it make sense to have a few lines of documentation on how/when to use this file?

**Review by alesgenova — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/225)* status: 2 unresolved discussions, platform LGTM missing (waiting on @BetsyMcPhail)

___
*[.github/workflows/ci.yml, line 93 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/225#-MzLPM9i1ru1JJd1lStA:-MzLl9ly8jpSJU7rXL8b:b-rn6idv) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/0e07970a25c1a9279aca6fbfa5f5a05acee0963b/.github/workflows/ci.yml#L93)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

This test shows as passing when it was run on this PR but it is actually failing with `git: command not found`
</blockquote></details>

I made changes to ensure that the action will actually fail if an error occurs (and also fixed the error that was happening)
___
*[scripts/setup/utils/update_setup_files.sh, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/225#-MzLTKXe8rdpQ3KPgN4e:-MzLlORkAK5bi0hpKm8Q:b-f1m16r) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/0e07970a25c1a9279aca6fbfa5f5a05acee0963b/scripts/setup/utils/update_setup_files.sh#L1)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Would it make sense to have a few lines of documentation on how/when to use this file?
</blockquote></details>

Added a short explanation of what the script does

**Review by BetsyMcPhail — APPROVED** [review]
Verified that the test ran successfully. :lgtm: 

+@jwnimmer-tri for review please

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/225#-:-MzLwIsa1XwzkVapxZYv:bidj3s4)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Is this PR fully finished?  My recollection from the last Kitware/TRI sync meeting was that it was known to be incomplete and is still being reworked.  Let me know whether I should start my review.

**Comment by jwnimmer-tri** [comment]
Hearing nothing, I'll de-assign myself in order to clean up my reviews dashboard.  Feel free to re-add me once it's ready.

**Pull request closed without merging**
