### PR TITLE
Remove unused CTestConfig.cmake

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Configuring CDash submissions is currently not supported by this repository

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/340)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@nicolecheetham for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/340#-:-OBgb12vCPeU_-H9TDdn:b-y76idi)* status: all discussions resolved, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

**Review by nicolecheetham — APPROVED** [review]
Assuming the last jenkins job is successful, :lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/340#-:-OBkGmHXCs8Lmf2Y9fbm:b-m0w1jw)* status: all discussions resolved, platform LGTM missing

**Review by nicolecheetham — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/340#-:-OBkH0ge3dAr-vmf3n8v:bnfp4nl)* status: all discussions resolved, platform LGTM missing

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/340#-:-OC-7HZX3Mt8Bwtum5px:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @nicolecheetham)

**Pull request merged**
