### PR TITLE
setup: incorporate latest changes from drake

### PR DESCRIPTION
**Pull request by jamiesnape**
This is probably at least two updates worth of changes from Drake.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/192)

### CODE REVIEW

**Comment by jamiesnape** [comment]
`ci / macos catalina 10.15 (pull_request)` failure is expected until the day after RobotLocomotion/drake#14395 merges.

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for review.

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm: as a strict improvement

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/192#-:-MNeJZkiBLUYgyC9gRBZ:bjemcjh)* status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri]

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/192#-MNeJmdyEmJIN5tRrp7t:-MNeJmdyEmJIN5tRrp7u:b-sksov) (no related file):*
BTW I'm at a loss as to why we still need the other dependencies beyond `./share/drake/setup/install_prereqs`.

Is it for usage of Bazel?
If so, is it possible to just for us to bundle something like `./share/drake/setup/install_prereqs/install_prereqs_bazel`?

---

**Comment by EricCousineau-TRI** [comment]
Relates #61

**Pull request merged**
