### PR TITLE
Add pandas to prerequisites

### PR DESCRIPTION
**Pull request by jamiesnape**
Required since RobotLocomotion/drake@426a52a9be5f8347cae6f14e67b95dec9075ebf6. Ideally, I do not feel the code in question here should really have to run, but this gets everything green/blue again for now.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/165)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review. CC @m-chaturvedi.

**Comment by jwnimmer-tri** [comment]
Given #61, we are not keeping the dependency lists 1:1 identical anyway.  Since the only reason the Drake commit is breaking drake-external-examples is because it is buggy, what do you think about fixing the bug in Drake instead of adding a heavy new dependency here?

**Comment by jamiesnape** [comment]
I would prefer that, but I do not want CI to be red for too long. We can leave this to sit while @m-chaturvedi investigates.

**Comment by jwnimmer-tri** [comment]
I support minimizing red.  We should never be afraid to revert, either.

**Comment by jamiesnape** [comment]
True. If you want to revert, I am fine by that.

**Pull request closed without merging**
