### PR TITLE
Upgrade cmake configuration to use C++20

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/284)

### CODE REVIEW

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm: thanks!

+@jwnimmer-tri 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/284#-:-Nrk6tpq1yNH7WUW5_CT:b19ry7j)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
@jwnimmer-tri I don't have merge permissions. Do we typically do platform review here?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/284#-:-NrkJ5eL3PwuDFnsnngW:b-ah1642)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @SeanCurtis-TRI)

**Comment by jwnimmer-tri** [comment]
We can call "single reviewer ok" on this.

But you _should_ have merge permissions.  Can you reload and check again?  Or check the github.com page instead of reviewable?

**Comment by SeanCurtis-TRI** [comment]
Nope. I still have this:

image

**Comment by jwnimmer-tri** [comment]
The settings _seemed_ like they should have been OK.  I tried changing some things that might help.  Try again?

**Comment by SeanCurtis-TRI** [comment]
Yep. As you can now tell, the twiddling worked.

**Pull request merged**
