### PR TITLE
Switch to Python 3.11 on Mac

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/18252

- [x] Revert https://github.com/RobotLocomotion/drake-external-examples/pull/250
- [X] Blocked by: https://github.com/RobotLocomotion/drake/pull/18262

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/248)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@svenevs for review please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/248#-:-NJQyMKX8-vYilcxrig-:b-m8sb1l)* status: all discussions resolved, LGTM missing from assignee svenevs, platform LGTM missing (waiting on @svenevs)

**Comment by svenevs** [comment]
I think we co-merge this with https://github.com/RobotLocomotion/drake/pull/18262.  Fix for broken setup is in #250

**Review by svenevs — APPROVED** [review]
-(status: not ready for review) -(status: not ready to merge) +@rpoyner-tri for platform review please now that CI is confirmed happy.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/248#-:-NOFpugQBAVooxPxW6HP:b-sktx87)* status: all discussions resolved, LGTM missing from assignee svenevs, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @rpoyner-tri)

**Review by svenevs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/248#-:-NOFqCvE220r0LDPnQ7g:bnfp4nl)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @rpoyner-tri)

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/248#-:-NOFvHsi-bp8W93oLw0_:bnfp4nl)* status: :shipit: complete! all discussions resolved, platform LGTM from [rpoyner-tri] (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
Try again now.  For some platform reviewers were `Maintain` instead of `Write` in the ACLs.

**Review by rpoyner-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/248)* status: :shipit: complete! all discussions resolved, platform LGTM from [rpoyner-tri] (waiting on @BetsyMcPhail)

**Review by rpoyner-tri — APPROVED** [review]
Still getting merge error. :shrug: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/248#-:-NOFxwQW2ehCjOyxUgUn:b-a3dmfg)* status: :shipit: complete! all discussions resolved, platform LGTM from [rpoyner-tri] (waiting on @BetsyMcPhail)

**Pull request merged**
