### PR TITLE
Pin bazel version to 5.2.0 to work around drake#17763

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/235)

### CODE REVIEW

**Review by ggould-tri — COMMENTED** [review]
+@svenevs for review.
I don't normally commit to this repo, so let me know if there are procedures I need to be following.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/235#-:-NAAf83e9L3G3F0b3WfA:b472rg3)* status: all discussions resolved, LGTM missing from assignee svenevs, platform LGTM missing (waiting on @svenevs)

**Review by svenevs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/235#-:-NAArZYpD89TnGOWqiD1:bnfp4nl)* status: all discussions resolved, platform LGTM missing (waiting on @ggould-tri)

**Review by rpoyner-tri — COMMENTED** [review]
Hm. Do we want to track https://github.com/RobotLocomotion/drake/pull/17764 and pin 5.1 instead?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/235#-:-NAAufvO6qRp0BULy3QI:b-9qlr2t)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @rpoyner-tri)

**Review by ggould-tri — COMMENTED** [review]
It would have been using 5.2 prior to today, so this is restoring status quo ante.
IMO, if the ultimate objective is for this to use head bazel as in the past, and we have a brief exception here, then 5.2 is the logical choice as it's both what we did before and also closest to head.
If on the other hand the objective is to get d-e-e to consume a bazel version from drake and we just temporarily don't have the plumbing yet, 5.1.0 makes more sense.
But I'm not sure what the original objective of d-e-e using bazel head was.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/235#-:-NAAv4jyE1gw_HfpJ7dN:b-7c94vv)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @rpoyner-tri)

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/235#-:-NAB2O_q34tdPF7YYWy3:bnfp4nl)* status: all discussions resolved, platform LGTM missing (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
Somehow I seem to be marked as a reviewer here?  -@ggould-tri ?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/235#-:-NAB3Lmn1zVdOS6uEVQU:b-rm16uf)* status: all discussions resolved, platform LGTM missing (waiting on @ggould-tri)

**Review by rpoyner-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/235)* status: all discussions resolved, platform LGTM missing (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
Hm, that didn't work.  +@ggould-tri :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/235#-:-NAB3aPO7dCsQNLNFza3:b-gfgnfr)* status: :shipit: complete! all discussions resolved, platform LGTM from [ggould-tri] (waiting on @ggould-tri)

**Review by rpoyner-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/235)* status: :shipit: complete! all discussions resolved, platform LGTM from [ggould-tri] (waiting on @ggould-tri)

**Pull request merged**
