### PR TITLE
Cleanup external prereqs

### PR DESCRIPTION
**Pull request by nicolecheetham**
Removes unneeded packages in the external install_prereqs

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/334)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/334)* status: 2 unresolved discussions, platform LGTM missing (waiting on @jwnimmer-tri and @nicolecheetham)

___
*[`drake_bazel_external/setup/install_prereqs` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/334#-OAOSB76ES4jSlPqAR0G:-OAOUcfv1Nt3aOJWKzkF:b-ttq61c) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/ac5ac943fb33a2aef356f575fa47b9586046c35d/drake_bazel_external/setup/install_prereqs#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This (and the call to the unzipped `install_prereqs` about 10 lines later) is entirely wrong.  It's downloading the binary release, which not NOT be part of building Drake from source.

This script should be downloading a _source_ copy of Drake, and then shelling out to the _source_ copy of `install_prereqs`.
</blockquote></details>

Nicole, take a look at `drake_bazel_external/setup/install_prereqs` in #313 (draft), I was able to remove all but one or two explicit installs after calling source copy of `install_prereqs`.

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/334)* status: 2 unresolved discussions, platform LGTM missing (waiting on @jwnimmer-tri and @nicolecheetham)

___
*[`drake_bazel_external/setup/install_prereqs` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/334#-OAOSB76ES4jSlPqAR0G:-OAOWCgZ1yyg7CF9v7WK:b-o4qpl8) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/ac5ac943fb33a2aef356f575fa47b9586046c35d/drake_bazel_external/setup/install_prereqs#L54)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Nicole, take a look at `drake_bazel_external/setup/install_prereqs` in #313 (draft), I was able to remove all but one or two explicit installs after calling source copy of `install_prereqs`.
</blockquote></details>

It's still feels not-quite-right as the CMake then adds drake as an external project (https://github.com/RobotLocomotion/drake-external-examples/blob/ed26e4261fe4c00c432eb321f4ea5dd8ac055ba1/drake_cmake_external/CMakeLists.txt#L98) and gets the source again.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/334)* status: 2 unresolved discussions, platform LGTM missing (waiting on @BetsyMcPhail and @nicolecheetham)

___
*[`drake_bazel_external/setup/install_prereqs` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/334#-OAOSB76ES4jSlPqAR0G:-OAOWjP8Azv0CTwPDf3L:b-jypowb) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/ac5ac943fb33a2aef356f575fa47b9586046c35d/drake_bazel_external/setup/install_prereqs#L54)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

It's still feels not-quite-right as the CMake then adds drake as an external project (https://github.com/RobotLocomotion/drake-external-examples/blob/ed26e4261fe4c00c432eb321f4ea5dd8ac055ba1/drake_cmake_external/CMakeLists.txt#L98) and gets the source again.
</blockquote></details>

Ah.  Maybe we should just close this PR and work on finishing up #313 instead?

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/334)* status: 2 unresolved discussions, platform LGTM missing (waiting on @jwnimmer-tri and @nicolecheetham)

___
*[`drake_bazel_external/setup/install_prereqs` line 54 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/334#-OAOSB76ES4jSlPqAR0G:-OAOWzIU9RqY-tcUMdvH:by9xj60) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/ac5ac943fb33a2aef356f575fa47b9586046c35d/drake_bazel_external/setup/install_prereqs#L54)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah.  Maybe we should just close this PR and work on finishing up #313 instead?
</blockquote></details>

That's fine with me, I haven't quite worked out the best way to structure the external examples. But  there's more work beyond just the `install_prereqs`.

**Pull request closed without merging**
