### PR TITLE
Update CMake python use for drake_cmake_external

### PR DESCRIPTION
**Pull request by nicolecheetham**
Update CMakeLists.txt use of finding the python package and the python executable

Issue: https://github.com/RobotLocomotion/drake/issues/21099

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/296)

### CODE REVIEW

**Review by nicolecheetham — COMMENTED** [review]
+@BetsyMcPhail for review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/296#-:-O4qLJypARHlyGztxXc5:b6t817a)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/296)* status: 1 unresolved discussion, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @nicolecheetham)

___
*[`drake_cmake_external/CMakeLists.txt` line 27 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/296#-O4rK54AE5AgwwfDjAXg:-O4rK54AE5AgwwfDjAXh:b-twnkm1) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/7c68ce1ab3fd35cba13c29625704eea7ea162261/drake_cmake_external/CMakeLists.txt#L27)):*
> ```CMake
> list(APPEND CMAKE_PREFIX_PATH "${CMAKE_INSTALL_PREFIX}")
> 
> if(APPLE)
> ```

BTW From here down to find_package(Python3 ... sets variables that are no longer used and can be removed?

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/296#-:-O4rKbBnCRT9M5n8Fq64:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
+@xuchenhan-tri for platform review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/296#-:-O4uac-C8nS8BNJ3ymER:b-he5s78)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri, platform LGTM from [betsymcphail] (waiting on @BetsyMcPhail and @xuchenhan-tri)

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/296#-:-O4ubKn-16Zwlm5iu6Uj:bnfp4nl)* status: all discussions resolved, LGTM missing from assignee xuchenhan-tri, platform LGTM from [betsymcphail] (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/296#-:-O4v-Byu0S0DVI2pQx46:bg7igkv)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @nicolecheetham)

**Review by xuchenhan-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/296#-:-O4v-E5oEGxPI5qH2VS4:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @nicolecheetham)

**Pull request merged**
