### PR TITLE
Unpack in $HOME instead of `/opt`

### PR DESCRIPTION
**Pull request by williamjallen**
Closes https://github.com/RobotLocomotion/drake/issues/10550

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/258)

### CODE REVIEW

**Review by BetsyMcPhail — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/258)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri and @williamjallen)

___
*[`drake_cmake_installed/README.md` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/258#-NN2uTuS0OcaDo1MtflF:-NN2uTuS0OcaDo1MtflG:b-1nnc3c) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/1402f9d39757a2fa4f9e3ca1dc5a6468ade6de4a/drake_cmake_installed/README.md#L33)):*
> ```Markdown
> # 2) The latest (usually last night's build)
> curl -O https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-focal.tar.gz
> sudo tar -xvzf drake-latest-focal.tar.gz -C $HOME
> ```

Is sudo still required here?

**Review by williamjallen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/258)* status: 1 unresolved discussion, LGTM missing from assignee betsymcphail, platform LGTM from [jwnimmer-tri] (waiting on @BetsyMcPhail and @jwnimmer-tri)

___
*[`drake_cmake_installed/README.md` line 33 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/258#-NN2uTuS0OcaDo1MtflF:-NN2ys8f5e0WcfLdkLpX:bxv4dhg) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/1402f9d39757a2fa4f9e3ca1dc5a6468ade6de4a/drake_cmake_installed/README.md#L33)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Is sudo still required here?
</blockquote></details>

The sudo seems to be unnecessary.  Removed.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/258)* status: 1 unresolved discussion, LGTM missing from assignee betsymcphail, platform LGTM from [jwnimmer-tri] (waiting on @BetsyMcPhail)

**Comment by jwnimmer-tri** [comment]
@BetsyMcPhail looks like this needs a re-look from you.

The CI failure seems like the flake from last week.  Pushing a new update to trigger a rebuild should resolve it, I think.

**Review by BetsyMcPhail — APPROVED** [review]
tested locally, :lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/258#-:-NNi-93W7W0vgC0PfMYC:b-g6wo36)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @williamjallen)

**Pull request merged**
