### PR TITLE
Cancel previous CI runs when new commits are added 

### PR DESCRIPTION
**Pull request by williamjallen**
GitHub Actions running for previous commits will now be halted when new commits are pushed to a pull request or to `main`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
+@svenevs for feature review.  I was taking a look at the docs over there and have some concerns over the [use of `${ github.token }`](https://github.com/styfle/cancel-workflow-action#advanced-token-permissions).  But I also scoped https://github.com/styfle/cancel-workflow-action/issues/191 which seems to indicate that we should be able to get equivalent functionality using the now [builtin `concurrency` specification](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency).  Are you willing to give that a shot instead?

For final review I think probably just me adding a dummy commit, push, revert, push, see if the jobs cancel could be OK -- we'll just squash everything at the end?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255#-:-NLeSZew377yxKa5ALny:b-6365za)* status: all discussions resolved, LGTM missing from assignee svenevs, platform LGTM missing

**Review by williamjallen — COMMENTED** [review]
`concurrency` definitely seems like the modern way to do it.  I was using another project which has had this functionality for a while as an example and it seems that GitHub has introduced this behavior natively now.

I'll make the updates and then we can test the way you suggested and squash the commits.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255#-:-NLcxA2l-6WfTxky9QFY:bgakr9s)* status: all discussions resolved, LGTM missing from assignee svenevs, platform LGTM missing (waiting on @svenevs)

**Review by svenevs — CHANGES_REQUESTED** [review]
Cancellation is closer, still some more steps to look into.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255#-:-NNhe1-a4_QXkmB3eHwC:b-stva5m)* status: 3 unresolved discussions, LGTM missing from assignee svenevs, platform LGTM missing (waiting on @williamjallen)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255#-NNhbrUfCkhfy93LeuGS):*
Working, Squash these all down to one when we're ready to be done please.
___
*[`.github/workflows/ci.yml` line 45 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255#-NNhdGG7AtAoGpu59QqF:-NNhdGG7AtAoGpu59QqG:bl6e42j) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/6af18816e4e0e5cc47d1246e64ef700ad67a3d1b/.github/workflows/ci.yml#L45)):*
> ```YAML
>     name: macos monterey 12
>     runs-on: macos-12
>     concurrency:
> ```

Separate thread, `cancel-in-progress: true` does not appear correct here.  We only want to do this for pull request builds.  Consider for example two commits getting merged from PRs very close to each other, this will cancel the earlier one when the second commit runs.

I'm pretty sure we only want to do this cancellation if it is a pull request.  I did not look closely but I think the expression desired is `cancel-in-progress: ${{ github.event_name == 'pull_request' }}
___
*[`.github/workflows/ci.yml` line 47 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255#-NNhbv0aEuDrxMUgF_SD:-NNhbv0aEuDrxMUgF_SE:b-s0sp6h) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/6af18816e4e0e5cc47d1246e64ef700ad67a3d1b/.github/workflows/ci.yml#L47)):*
> ```YAML
>     concurrency:
>       group: ${{ github.head_ref || github.run_id }}
>       cancel-in-progress: true
> ```

It works.  Now added it to every other runner.  Refs: https://github.com/RobotLocomotion/drake-external-examples/actions/runs/4118040998

Only macOS got cancelled because that's the only thing this PR is changing.  Needs to cancel everywhere else too:

https://github.com/RobotLocomotion/drake-external-examples/blob/25b71176496c8b9a29334f836826044d1a480bac/.github/workflows/ci.yml#L54

https://github.com/RobotLocomotion/drake-external-examples/blob/25b71176496c8b9a29334f836826044d1a480bac/.github/workflows/ci.yml#L67

https://github.com/RobotLocomotion/drake-external-examples/blob/25b71176496c8b9a29334f836826044d1a480bac/.github/workflows/ci.yml#L80

alternatively it may be possible to just add it at the top before `jobs:`, from what I can tell from the docs it can go there too.  Either way let's add a brief comment `# Cancel previous runs of this workflow when a new one starts.` or something.

**Review by svenevs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255)* status: 3 unresolved discussions, LGTM missing from assignee svenevs, platform LGTM missing (waiting on @williamjallen)

___
*[`.github/workflows/ci.yml` line 45 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255#-NNhdGG7AtAoGpu59QqF:-NNheFeH6p1HXc_ZWGml:b-bd9i7r) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/6af18816e4e0e5cc47d1246e64ef700ad67a3d1b/.github/workflows/ci.yml#L45)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Separate thread, `cancel-in-progress: true` does not appear correct here.  We only want to do this for pull request builds.  Consider for example two commits getting merged from PRs very close to each other, this will cancel the earlier one when the second commit runs.

I'm pretty sure we only want to do this cancellation if it is a pull request.  I did not look closely but I think the expression desired is `cancel-in-progress: ${{ github.event_name == 'pull_request' }}
</blockquote></details>

https://github.com/RobotLocomotion/drake-external-examples/blob/25b71176496c8b9a29334f836826044d1a480bac/.github/workflows/ci.yml#L32

refs: it's triggered by branch pushes and runs on a schedule.

**Review by williamjallen — COMMENTED** [review]
I'll squash all of the commits into a single readable commit when I'm done testing things.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255#-:-NNlgjP00CbqHwFWV3a0:b-u0o6vt)* status: 3 unresolved discussions, LGTM missing from assignee svenevs, platform LGTM missing (waiting on @svenevs)

___
*[`.github/workflows/ci.yml` line 45 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255#-NNhdGG7AtAoGpu59QqF:-NNlfo-j3ge4hGYej1Va:b-hj3hx2) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/6af18816e4e0e5cc47d1246e64ef700ad67a3d1b/.github/workflows/ci.yml#L45)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

https://github.com/RobotLocomotion/drake-external-examples/blob/25b71176496c8b9a29334f836826044d1a480bac/.github/workflows/ci.yml#L32

refs: it's triggered by branch pushes and runs on a schedule.
</blockquote></details>

As per [these](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value) docs, I believe that this will only cancel `pull_request` runs since `github.head_ref` will be undefined and each run will have a unique `github.run_id` on pushes.  That said, I'm still working to verify that this is correct.
___
*[`.github/workflows/ci.yml` line 47 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/255#-NNhbv0aEuDrxMUgF_SD:-NNlgdHy6Iqdhi3et5L7:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/6af18816e4e0e5cc47d1246e64ef700ad67a3d1b/.github/workflows/ci.yml#L47)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

It works.  Now added it to every other runner.  Refs: https://github.com/RobotLocomotion/drake-external-examples/actions/runs/4118040998

Only macOS got cancelled because that's the only thing this PR is changing.  Needs to cancel everywhere else too:

https://github.com/RobotLocomotion/drake-external-examples/blob/25b71176496c8b9a29334f836826044d1a480bac/.github/workflows/ci.yml#L54

https://github.com/RobotLocomotion/drake-external-examples/blob/25b71176496c8b9a29334f836826044d1a480bac/.github/workflows/ci.yml#L67

https://github.com/RobotLocomotion/drake-external-examples/blob/25b71176496c8b9a29334f836826044d1a480bac/.github/workflows/ci.yml#L80

alternatively it may be possible to just add it at the top before `jobs:`, from what I can tell from the docs it can go there too.  Either way let's add a brief comment `# Cancel previous runs of this workflow when a new one starts.` or something.
</blockquote></details>

Done.

**Comment by svenevs** [comment]
Moved to #261 to verify `branch` runs on this repo rather than needing to verify on the fork.

**Pull request closed without merging**
