### PR TITLE
[setup] Hotfix for brew failing to upgrade python@3.11

### PR DESCRIPTION
**Pull request by svenevs**
Continuation of #250.

Relates: https://github.com/actions/setup-python/issues/577

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/252)

### CODE REVIEW

**Comment by svenevs** [comment]
Build uses 3.10 as desired:

```
-- Found PythonInterp: /usr/local/bin/python3.10 (found suitable exact version "3.10.9") 
-- Found PythonLibs: /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib (found suitable exact version "3.10.9") 
-- Found PythonInterp: /usr/local/bin/python3.10 (found version "3.10.9") 
-- Found PythonLibs: /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib (found version "3.10.9") 
-- Found PythonLibs: /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/libpython3.10.dylib
```

**Review by svenevs — COMMENTED** [review]
+@BetsyMcPhail for review please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/252#-:-NKsRmGR9sQcXpZFrI4I:bf1mnay)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/252#-:-NKsTxC41GyFDdfrHVRn:bnfp4nl)* status: all discussions resolved, platform LGTM missing (waiting on @svenevs)

**Review by svenevs — COMMENTED** [review]
+@rpoyner-tri for drive-by platform review per schedule please.  CI is passing again with these changes :partying_face:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/252#-:-NKsXCmABViG4GeE3XXu:b9388kq)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @rpoyner-tri)

**Review by rpoyner-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/252)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @svenevs)

___
*[`.github/workflows/ci.yml` line 71 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/252#-NKsd2xx1RJBblQjkC20:-NKsd2xx1RJBblQjkC21:b7phl63) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/f73b79a94065e423f5eca0955952f9783f4757a0/.github/workflows/ci.yml#L71)):*
> ```YAML
>           rm -f /usr/local/bin/python3-config
> 
>           # New issues related to python@3.11 upgrades.
> ```

Minor there is some subtle stuff going on here -- we install both 3.10 and 3.11, but drake still uses 3.10. It would help maintainers to beef up this comment a little bit. Maybe at least reference the underlying issue, and suggest how this extra code might sunset?

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/252)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @svenevs)

___
*[`.github/workflows/ci.yml` line 71 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/252#-NKsd2xx1RJBblQjkC20:-NKslHD23H9J-qBvamU6:b8zg0sl) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/f73b79a94065e423f5eca0955952f9783f4757a0/.github/workflows/ci.yml#L71)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Minor there is some subtle stuff going on here -- we install both 3.10 and 3.11, but drake still uses 3.10. It would help maintainers to beef up this comment a little bit. Maybe at least reference the underlying issue, and suggest how this extra code might sunset?
</blockquote></details>

Done, I believe.  I updated the comment for the whole `sanitize brew` section, the truth is we're flying a little blind here.  I believe the underlying issue is "too many python's installed in the GHA brew image", plus the brew python formula not correctly uninstalling symlinks (?).  We're going to try and remove it in the python 3.11 update, but it may have to linger (in which case we'll update the comment).

**Review by rpoyner-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/252)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @svenevs)

___
*[`.github/workflows/ci.yml` line 71 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/252#-NKsd2xx1RJBblQjkC20:-NKsnW7g9ThyfSiIBLJR:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/f73b79a94065e423f5eca0955952f9783f4757a0/.github/workflows/ci.yml#L71)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Done, I believe.  I updated the comment for the whole `sanitize brew` section, the truth is we're flying a little blind here.  I believe the underlying issue is "too many python's installed in the GHA brew image", plus the brew python formula not correctly uninstalling symlinks (?).  We're going to try and remove it in the python 3.11 update, but it may have to linger (in which case we'll update the comment).
</blockquote></details>

Thanks!

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/252#-:-NKsncY58rx6xYZvpjNt:bnfp4nl)* status: :shipit: complete! all discussions resolved, platform LGTM from [rpoyner-tri] (waiting on @svenevs)

**Pull request merged**
