### PR TITLE
Mac GHA: Remove workarounds that are no longer needed

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards https://github.com/RobotLocomotion/drake/issues/22009

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/323)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@nicolecheetham for review please. Note the mac job will still fail until the new nightly packages are created tonight.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/323#-:-O8rzDsO15lF2pHIbm_H:bn9s9kr)* status: all discussions resolved, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

**Review by nicolecheetham — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/323#-:-O8sEilM864x3zLaJbC0:bnfp4nl)* status: all discussions resolved, platform LGTM missing

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/323#-:-O8w9Qp0Ab5bQmXY6iPS:b1f7mq7)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri and @nicolecheetham)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/323#-:-O8wEUx6DkdfzeaglPoJ:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [jwnimmer-tri] (waiting on @BetsyMcPhail and @nicolecheetham)

___
*[`.github/workflows/ci.yml` line 37 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/323#-O8wEOaV2X8aigXy-qEZ:-O8wEOaWEu4Rh-2L05dq:b4v6b1m) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/697715d34fb020dd917da7998d5f7524356da4af/.github/workflows/ci.yml#L37)):*
> ```YAML
>           find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
>           sudo rm -rf /Library/Frameworks/Python.framework/
> ```

nit It seems in this file we typically don't use blank lines spacing things out like this?

**Review by nicolecheetham — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/323#-:-O8wZSP59TVXNLrDjrl6:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @jwnimmer-tri)

**Pull request merged**
