### PR TITLE
Add find_resource_test C++ example

### LINKED ISSUE #210: [drake_bazel_installed] C++ Examples for Bazel when Using with Installed Package
Are there any example of how to use bazel when install drake as the external library?

I checked out **/opt/drake/share/drake/repo.bzl** and found out the following:
```
147 # TODO(jwnimmer-tri) Use the correct cc_import phrasing, then mark this public.
148 filegroup(
149     name = ".drake_shared_library",
150     data = glob([
151     ┆   ".lib/*.so",
152     ┆   ".lib/*.so.*",
153     ]),
154 )
```

I am pretty new to bazel, but I think this meant that I have to write a bazel rule by myself. 
Do you have an example of such bazel rule which would allow me to do the following?
```
    deps = [
          "@drake//:drake_shared_library",
    ],
```

P.S. I am aware of "drake_bazel_external", but compiling drake simply took too long on my machine.

### PR DESCRIPTION
**Pull request by sloretz**
Closes #210
Context: https://github.com/RobotLocomotion/drake-ros/pull/75#pullrequestreview-955704403

+@EricCousineau-TRI for review please

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226)

### CODE REVIEW

**Review by EricCousineau-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226)* status: 2 unresolved discussions, platform LGTM missing (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226#-N16QL6s22lrnSTmETiD:-N16QL6s22lrnSTmETiE:bbrzw56) (no related file):*
Working: Unclear why we encountered this failure on CI:
```
[FATAL 00:41:16.291 src/main/cpp/blaze.cc:1295] Unexpected error reading .blazerc file '/media/ephemeral0/ubuntu/workspace/n_drake-external-examples_PR-226/src/drake_cmake_external/build/drake-prefix/src/drake/gen/environment.bazelrc'
```
(I think it's unrelated?)

@jwnimmer-tri Any chance this is something you've seen before?

---
___
*[`drake_bazel_installed/apps/BUILD.bazel` line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226#-N16QZZS4BJvICTQMSZC:-N16QZZT2m_dg2Le0un4:bjjau5i) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/715eb144dc9f4d79f8a0759f03ffaa2ba869bfff/drake_bazel_installed/apps/BUILD.bazel#L61)):*
> ```Starlark
>     ],
>     data = [
>         # TODO(sloretz) want smaller scope visible target access to
> ```

Working: Unclear why we need `pydrake` here; I would have thought that `drake_shared_library` should have brought in this relevant data.

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226#-N16QL6s22lrnSTmETiD:-N16qFT6BaYL0AJjlHS0:b-n6c98b) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Unclear why we encountered this failure on CI:
```
[FATAL 00:41:16.291 src/main/cpp/blaze.cc:1295] Unexpected error reading .blazerc file '/media/ephemeral0/ubuntu/workspace/n_drake-external-examples_PR-226/src/drake_cmake_external/build/drake-prefix/src/drake/gen/environment.bazelrc'
```
(I think it's unrelated?)

@jwnimmer-tri Any chance this is something you've seen before?
</blockquote></details>

This is probably a regression today on Drake master (unrelated to this PR) that will need to be reverted.

---

**Review by sloretz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226)* status: 2 unresolved discussions, platform LGTM missing (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`drake_bazel_installed/apps/BUILD.bazel` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226#-N16TGAf009ij226UHhX:-N1B2JzRBvE0kZklwmhG:b-kn0fli) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/715eb144dc9f4d79f8a0759f03ffaa2ba869bfff/drake_bazel_installed/apps/BUILD.bazel#L55)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Suffix with `_cc` is a bit odd, esp. if not ending with `_test`.

We should ideally qualify the other targets, and change it to be `_cc_test` or `_py_test`.
Can you change test targets to end with either `_cc_test` or `_py_test`?

Consider
</blockquote></details>

Suffixed with `_cct_test` and `_py_test` in b6ce4a3

**Comment by jwnimmer-tri** [comment]
FYI possibly this PR should close issue #210.  (We can let the reviewer(s) decide.)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm_strong: 
Set this up to close the issue.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226#-:-N1lA49tDxnqeWtTfWO_:bq5x0op)* status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri] (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226#-N16QL6s22lrnSTmETiD:-N1l9QfA84Wka22_R-SM:b-w196av) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is probably a regression today on Drake master (unrelated to this PR) that will need to be reverted.
</blockquote></details>

OK Thanks!

___
___
*[`drake_bazel_installed/apps/BUILD.bazel` line 55 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226#-N16TGAf009ij226UHhX:-N1l9UHvDlsdOSlmkJQY:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/715eb144dc9f4d79f8a0759f03ffaa2ba869bfff/drake_bazel_installed/apps/BUILD.bazel#L55)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Suffixed with `_cct_test` and `_py_test` in b6ce4a3
</blockquote></details>

OK Thanks!
___
*[`drake_bazel_installed/apps/BUILD.bazel` line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226#-N16QZZS4BJvICTQMSZC:-N1l9WNt7HfSqc7g2Cp4:bkx6fa4) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/715eb144dc9f4d79f8a0759f03ffaa2ba869bfff/drake_bazel_installed/apps/BUILD.bazel#L61)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Confirmed. Asking for advice on Drake Slack.
</blockquote></details>

OK Per Drake Slack:
- This is expected. Would need to add more `data = []` targets into the binary form of Bazel rule - however
- The `drake_bazel_installed` (binary) form of consumption is really only well supported for Python only, but not so much for C++.

This PR stands as a strict improvement, but for `drake-ros`, we will go the route of testing against `drake_bazel_external` (source) on CI and try to fit within budgets of GitHub actions by leveraging caching.

Beyond that, no plan for further action in near future.

**Review by EricCousineau-TRI — APPROVED** [review]

**Comment by EricCousineau-TRI** [comment]
ah, oops :facepalm: meant to remove `Signed-Off-By` - sorry!

**Comment by jwnimmer-tri** [comment]
*[`drake_bazel_installed/apps/BUILD.bazel` line 61 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/226#-N16QZZS4BJvICTQMSZC:-NU2d5OR4v5jphlod8aV:b-f7egl2) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/715eb144dc9f4d79f8a0759f03ffaa2ba869bfff/drake_bazel_installed/apps/BUILD.bazel#L61)):*
That's not what I said in slack.  I said:

> I think it would be OK for the :drake_shared_library target in the installed drake.BUILD.bazel to depend on all of the runfiles, similar to how pydrake already does.

Add pydrake as a hack to make the test pass completely masked the bug that drake_shared_library is completely broken.  We can't even load `drake/package.xml` without this hack.

I'm fixing it in https://github.com/RobotLocomotion/drake/pull/19294 now.

**Pull request merged**
