### PR TITLE
Move ubuntu ros and apt setups to relevant example

### PR DESCRIPTION
**Pull request by nicolecheetham**
Moves the various GHA setups to the relevant drake example location(s).

Issue: https://github.com/RobotLocomotion/drake-external-examples/issues/309

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/316)

### CODE REVIEW

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/316#-:-O7VcY52BcJDA4TqlUQ2:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
+@rpoyner-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/316#-:-O7ZbSAH8xCyGn69Wa6C:b-hnc6mz)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM from [betsymcphail] (waiting on @rpoyner-tri)

**Review by rpoyner-tri — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/316)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/316#-:-O7ZeKHO-OH6OZacL1Uf:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @nicolecheetham)

**Comment by jwnimmer-tri** [comment]
Ditto to #314, don't put CI-only details into the root folders.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/316)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @BetsyMcPhail and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/316#-O7_edp23EXP4TDA_pMV:-O7_f7vK2DOB0B4yA3NB:bj43i0w) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Is a hidden subdirectory (`.github`) what we want?
</blockquote></details>

My suggested policy would be:

Any code (& configs, etc) that is _solely_ intended for CI goes into that folder.  (The `.github/` hidden-ness is canonical for CI that uses GitHub Actions.)  If scripts are to be run by _humans_ e.g. on their laptop, then they should _not_ be in a hidden folder, rather in `setup/` or `tools/` or the like.

In this case the scripts are "configure system-wide apt retries and non-interactivity" which is definitely on the "CI only" side, not the "users do it" side.

___

**Review by rpoyner-tri — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/316)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @nicolecheetham)

**Pull request merged**
