### PR TITLE
Change build tests location to relevant example

### PR DESCRIPTION
**Pull request by nicolecheetham**
Moves the build tests located in the common directory to the specific drake example which uses them.

Issue: https://github.com/RobotLocomotion/drake-external-examples/issues/309

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/314)

### CODE REVIEW

**Review by nicolecheetham — COMMENTED** [review]
+@BetsyMcPhail  for feature review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/314#-:-O7UtM5F4FcW5J4D6Tro:b-x5oip4)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/314#-:-O7VcEwPA6FhlHX1w2pR:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
+@rpoyner-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/314#-:-O7ZamOX3lQ1x5uzN7Th:b-hnc6mz)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM from [betsymcphail] (waiting on @rpoyner-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
I can take this one +@jwnimmer-tri -@rpoyner-tri.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/314#-:-O7ZbOp5AuPZgvkn8JIl:bc8o4pl)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

**Review by jwnimmer-tri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/314)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/314#-O7ZbTSD5cp9yxbXxTVZ:-O7ZbTSD5cp9yxbXxTV_:bxjrr2b) (no related file):*
Details of CI should not live in the top-level folders.  They are details (i.e., distractions) so should not be given the prominence of sitting next to the main README.md, CMakeLists.txt, etc. for each example.

Possibly subdir names they could live would be e.g. `.github` or `.ci`, so in full that would be `drake-external-examples.git/drake_cmake_installed/.github/ci_build_test`.

___

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/314#-:-O7_jBxO3urbPoo_CRog:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, jwnimmer-tri] (waiting on @nicolecheetham)

**Pull request merged**
