### PR TITLE
Use InportPort.FixValue instead of Context.FixInputPort

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/190)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for review, please!
(low priority)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/190#-:-MLEd3bgEfpNpTRST_nL:b-ay5kh2)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/190#-:-MLEoGd9D9izjh_M3EEI:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [jwnimmer-tri] (waiting on @EricCousineau-TRI)

___
*[drake_ament_cmake_installed/src/drake_ament_cmake_installed/test/particle_test.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/190#-MLEmra28u5J4jGbUS03:-MLEmra33v91UeSqJ0zZ:bcy7g8u) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/e15aa03e4702047490e1ba14c965c10b794ce9e6/drake_ament_cmake_installed/src/drake_ament_cmake_installed/test/particle_test.cc#L48)):*
> ```cpp
> namespace {
> 
> using drake::VectorX;
> ```

nit None of the rest of the code here uses `using` statements.  It makes a clearer example that way.

(Ditto for all the copies of this file.)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/190)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @jwnimmer-tri)

___
*[drake_ament_cmake_installed/src/drake_ament_cmake_installed/test/particle_test.cc, line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/190#-MLEmra28u5J4jGbUS03:-MLEunnX5Au-TmsIiDIq:b9p12q0) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/e15aa03e4702047490e1ba14c965c10b794ce9e6/drake_ament_cmake_installed/src/drake_ament_cmake_installed/test/particle_test.cc#L48)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit None of the rest of the code here uses `using` statements.  It makes a clearer example that way.

(Ditto for all the copies of this file.)
</blockquote></details>

Done.

100% agree on "clearer for consistency", but do not agree on "clearer in isolation".

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/190)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

**Pull request merged**
