### PR TITLE
[ci] Sanitize GHA macOS brew issues with `node`

### PR DESCRIPTION
**Pull request by svenevs**
- [X] Waiting for green CI
- [Slack discussion](https://drakedevelopers.slack.com/archives/C270MN28G/p1695657429562159).

------

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271)

### CODE REVIEW

**Review by svenevs — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271)* status: 1 unresolved discussion, platform LGTM missing (waiting on @svenevs)

___
*[`.github/workflows/ci.yml` line 40 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271#-NfCFf3UDjbvs36W-UUx:-NfCFf3UDjbvs36W-UUy:b3l2wtw) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/2051ab71b8ea33d71402c771069b564d0af10024/.github/workflows/ci.yml#L40)):*
> ```YAML
>           brew unlink tcl-tk
>           # On 2023-04-06 `brew upgrade` resulted in a failure upgrading `go`.
>           brew unlink go && rm -f /usr/local/bin/go && rm -f /usr/local/bin/gofmt
> ```

working, current commit is able to get past sanitize brew step, but with the following output:

```
Unlinking /usr/local/Cellar/tcl-tk/8.6.13_5... 1746 symlinks removed.
Error: No such keg: /usr/local/Cellar/go
Unlinking /usr/local/Cellar/node@18/18.17.1... 2424 symlinks removed.
```

Going to try removing the line for go

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271)* status: 1 unresolved discussion, platform LGTM missing (waiting on @svenevs)

___
*[`.github/workflows/ci.yml` line 40 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271#-NfCFf3UDjbvs36W-UUx:-NfCHbku26niHRX9lsnv:b7udbrm) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/2051ab71b8ea33d71402c771069b564d0af10024/.github/workflows/ci.yml#L40)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

working, current commit is able to get past sanitize brew step, but with the following output:

```
Unlinking /usr/local/Cellar/tcl-tk/8.6.13_5... 1746 symlinks removed.
Error: No such keg: /usr/local/Cellar/go
Unlinking /usr/local/Cellar/node@18/18.17.1... 2424 symlinks removed.
```

Going to try removing the line for go
</blockquote></details>

Job log from that build still succeeds which is kind of interesting... https://github.com/RobotLocomotion/drake-external-examples/actions/runs/6302366628/job/17109394860?pr=271

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271)* status: all discussions resolved, platform LGTM missing (waiting on @svenevs)

___
*[`.github/workflows/ci.yml` line 40 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271#-NfCFf3UDjbvs36W-UUx:-NfCJ5FW0rjCAlZncis3:b-bs4orz) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/2051ab71b8ea33d71402c771069b564d0af10024/.github/workflows/ci.yml#L40)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

Job log from that build still succeeds which is kind of interesting... https://github.com/RobotLocomotion/drake-external-examples/actions/runs/6302366628/job/17109394860?pr=271
</blockquote></details>

done, `Error: No such keg: /usr/local/Cellar/go` is still there in https://github.com/RobotLocomotion/drake-external-examples/actions/runs/6302493320/job/17109806104?pr=271 but it doesn't appear to matter, and probably a small issue with the `go` formula or how GitHub Actions is setup.  Either way, not worth resolving

**Review by svenevs — COMMENTED** [review]
+@xuchenhan-tri for review please :slightly_smiling_face:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271#-:-NfCJjBs7n1vWKeyawwD:b-pmf07d)* status: all discussions resolved, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @xuchenhan-tri)

___
*[`.github/workflows/ci.yml` line 44 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271#-NfCJT5v44V3u9vZgjTg:-NfCJT5v44V3u9vZgjTh:b-2j0h8g) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/0a67e7efb11ec63e5d951a0f979898a822feb995/.github/workflows/ci.yml#L44)):*
> ```YAML
>           # The `brew list <formula>` will error if it is not installed.  When
>           # the logs say something like "No such keg: /some/path/<formula>"
>           # that means the band-aid can be removed from DEE CI.
> ```

FYI the new approach here appears to be possibly slightly more resilient so I'd like to keep it, but the `brew list && brew unlink` doesn't actually appear to be working in CI the way I expected, re the `go` formula, but `brew update && brew upgrade` are working again so we should land this.

**Review by xuchenhan-tri — APPROVED** [review]
:lgtm: 
+@BetsyMcPhail for another look just in case.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271#-:-NfCLMNX2L7o9oIN97vG:b-4y8ubp)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM from [xuchenhan-tri] (waiting on @BetsyMcPhail)

**Review by xuchenhan-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM from [xuchenhan-tri] (waiting on @BetsyMcPhail)

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM from [xuchenhan-tri] (waiting on @BetsyMcPhail)

___
*[`.github/workflows/ci.yml` line 47 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271#-NfCN92RA5COkCQbn6vg:-NfCN92RA5COkCQbn6vh:b-erto28) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/0a67e7efb11ec63e5d951a0f979898a822feb995/.github/workflows/ci.yml#L47)):*
> ```YAML
>           ######################################################################
>           # On 2023-02-24 `brew upgrade` resulted in a failure linking tcl-tk.
>           brew list tcl-tk && brew unlink tcl-tk
> ```

FYI @BetsyMcPhail the strategy here is to get it to fail early (that's the whole point of this section of the yaml).  There were some confusing messages about `brew unlink go` but it _does_ seem to still be installed.  There's no way to decouple our CI script from the _internal_ infrastructure choices for GHA, but in the future if `tcl-tk` is _not_ installed then this _should_ fail on `brew list tcl-tk` and we will be able to know then and there to remove it.

As it stands currently, all of our problem children (ptyhon, tcl-tk, go, now node) need special treatment.

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM from [xuchenhan-tri] (waiting on @svenevs)

**Review by BetsyMcPhail — APPROVED** [review]
CI is happy, :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/271#-:-NfC_6UGCBKh5d_CMecC:b-tuo6nz)* status: :shipit: complete! all discussions resolved, platform LGTM from [xuchenhan-tri, betsymcphail] (waiting on @svenevs)

**Pull request merged**
