### PR TITLE
install_prereqs: `cat` contents of VERSION.TXT for exact drake commit

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Per Drake Slack convo: https://drakedevelopers.slack.com/archives/C270MN28G/p1615387821041900?thread_ts=1615308431.035600&cid=C270MN28G

Ensure that we follow our own instructions: https://drake.mit.edu/getting_help.html

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/198)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jamiesnape for review, please!

\cc @rpoyner-tri @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/198#-:-MVSxNAL8d1x4ICrXcni:b7hqwm9)* status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing (waiting on @jamiesnape)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/198)* status: 1 unresolved discussion, LGTM missing from assignee jamiesnape, platform LGTM missing (waiting on @EricCousineau-TRI and @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/198#-MVSyjIg3ebLLHSpbxVV:-MVSyjIg3ebLLHSpbxVW:b-ctvpit) (no related file):*
Working: Currently unreadable, most likely due to mixing of stdin & stdout w/ GitHub UI

https://github.com/RobotLocomotion/drake-external-examples/pull/198/checks?check_run_id=2080924323#step:4:4440
```
+ tar -xf drake.tar.gz -C /opt
+ cat /opt/drake/share/doc/drake/VERSION.TXT
+ /opt/drake/share/drake/setup/install_prereqs
20210310080453 f23ea3a22d6428c91263fb80cce34a235fe1fff7Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
```

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/198)* status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing (waiting on @jamiesnape)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/198#-MVSyjIg3ebLLHSpbxVV:-MVT1z_o3R1DCSdlW128:b-7m66xd) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Currently unreadable, most likely due to mixing of stdin & stdout w/ GitHub UI

https://github.com/RobotLocomotion/drake-external-examples/pull/198/checks?check_run_id=2080924323#step:4:4440
```
+ tar -xf drake.tar.gz -C /opt
+ cat /opt/drake/share/doc/drake/VERSION.TXT
+ /opt/drake/share/drake/setup/install_prereqs
20210310080453 f23ea3a22d6428c91263fb80cce34a235fe1fff7Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
```
</blockquote></details>

Done. Not the best, but now it's readable:
https://github.com/RobotLocomotion/drake-external-examples/pull/198/checks?check_run_id=2080987134#step:3:883

```
 +./scripts/setup/mac/install_prereqs:49> tar -xf drake.tar.gz -C /opt
+./scripts/setup/mac/install_prereqs:52> cat /opt/drake/share/doc/drake/VERSION.TXT
+./scripts/setup/mac/install_prereqs:52> echo -e '\ndrake VERSION.TXT: 20210310040748 f23ea3a22d6428c91263fb80cce34a235fe1fff7\n'

+./scripts/setup/mac/install_prereqs:54> /opt/drake/share/drake/setup/install_prereqs
drake VERSION.TXT: 20210310040748 f23ea3a22d6428c91263fb80cce34a235fe1fff7
```

---

**Review by jamiesnape — APPROVED** [review]
Probably should check for the existence of the file (CI adds it, a local build would not have it), but for these purposes it should be there.

:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/198#-:-MVT4TT_DHnnV_jPEPpo:b-bg67tl)* status: :shipit: complete! all discussions resolved, platform LGTM from [jamiesnape] (waiting on @EricCousineau-TRI)

**Pull request merged**
