### PR TITLE
Fix ament cmake transitive dependency issue

### LINKED ISSUE #292: ament cmake transitive dependency issue
Following the drake_ament_cmake_installed, the package I have base_lib depends on drake builds without problem,
however another package that depends on base_lib throws error saying it cannot find drake::drake
```
CMake Error at /code/src/install/base_lib/share/base_lib/cmake/export_base_libExport.cmake:61 (set_target_properties):
  The link interface of target "base_lib::base_lib" contains:

    drake::drake

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /code/src/install/base_lib/share/base_lib/cmake/ament_cmake_export_targets-extras.cmake:9 (include)
  /code/src/install/base_lib/share/base_lib/cmake/base_libConfig.cmake:41 (include)
  CMakeLists.txt:19 (find_package)
```

My CMakeLists.txt
```
cmake_minimum_required(VERSION 3.10)
project(base_lib)
find_package(rclcpp_components REQUIRED)

# Default to C++14
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 20)
endif()

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package(ament_cmake REQUIRED)
# list(APPEND CMAKE_PREFIX_PATH /opt/drake)
find_package(drake CONFIG REQUIRED PATHS /opt/drake)
# find_package(drake CONFIG REQUIRED)

add_library(${PROJECT_NAME} SHARED
  src/param_utils.cc
  src/yaml_read_include.cc
  src/logger.cc
)

target_link_libraries(${PROJECT_NAME} drake::drake)

target_include_directories(${PROJECT_NAME} PUBLIC 
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)

# set_target_properties(${PROJECT_NAME} PROPERTIES EXPORT_HEADER_DIR "${CMAKE_CURRENT_BINARY_DIR}")

install(TARGETS ${PROJECT_NAME}
EXPORT export_${PROJECT_NAME}
  ARCHIVE DESTINATION lib
  LIBRARY DESTINATION lib
  RUNTIME DESTINATION bin
  INCLUDES DESTINATION include
)

# Export old-style CMake variables
# ament_export_libraries(${PROJECT_NAME})

# Export modern CMake targets

install(DIRECTORY include/ DESTINATION include/)

if(BUILD_TESTING)
  find_package(ament_cmake_gtest CONFIG REQUIRED)
  find_package(ament_lint_auto CONFIG REQUIRED)

  ament_add_gtest(${PROJECT_NAME}_test test/test_yaml.cc)
  target_link_libraries(${PROJECT_NAME}_test 
    ${PROJECT_NAME}
    rclcpp_components::component  
  )

  ament_lint_auto_find_test_dependencies()
endif()

ament_export_include_directories(include/${PROJECT_NAME})
ament_export_targets(export_${PROJECT_NAME})
ament_export_libraries(${PROJECT_NAME})

# ament_export_include_directories(include)

ament_package()
```
Any help would be greatly appreciated. Drake is installed properly to /opt/drake and I can build standalone packages that depends on drake

### PR DESCRIPTION
**Pull request by weithegreat**
The current amend cmake example build without problem, however there will be issue finding drake dependency for libraries depends on such a library

Closes #292.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/293)

### CODE REVIEW

**Comment by weithegreat** [comment]
@jwnimmer-tri  Hey Jeremy would you mind taking a look at this PR?

**Comment by jwnimmer-tri** [comment]
+@IanTheEngineer do you know any https://github.com/RobotLocomotion/drake-ros member who would like to review this?

To me, the ament part looks okay, but manually setting LD_LIBRARY_PATH is usually an obscenity and should be avoided with prejudice.  Hopefully there is another way to get it working.  I imagine the ament ecosystem already has some better way to deal with library paths?

**Comment by jwnimmer-tri** [comment]
@IanTheEngineer last call to find someone to support this ament example.

If we can't find anyone to support it, then I will merge this PR as-is and follow up by documenting the ament example as outside of our support footprint, i.e., "community maintained - PRs welcome" and remove it from CI.

**Comment by jwnimmer-tri** [comment]
I should probably ping @EricCousineau-TRI also.

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm: platform review.

+@IanTheEngineer for feature review, please.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> Dismissed @IanTheEngineer from a discussion.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/293#-:-OA4ymhu9Sk2VzL6sxy_:b-ru0goi)* status: all discussions resolved, LGTM missing from assignee iantheengineer, platform LGTM from [jwnimmer-tri] (waiting on @weithegreat)

___
*[`drake_ament_cmake_installed/README.md` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/293#-O7AN4gy5Wd-A5k4zk3a:-OA4ygBz3j8gnarVeHm-:b-1c90gu) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/65a4b33f9e76e4df187e7e548583f8669e74d1fa/drake_ament_cmake_installed/README.md#L18)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Does your environment work without adding this `LD_LIBRARY_PATH` export and only the `ament_export_dependencies(drake)` change below?

Depending on the reader's environment setup, this export could be problematic, particularly if multiple versions of Drake are added.
</blockquote></details>

Not hearing anything, we might as well just merge the CMake fix and leave this part for another day.  I reverted this part.

**Review by IanTheEngineer — APPROVED** [review]
:LGTM: for feature review. Thanks!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/293#-:-OAJefjz1sYIQwrvhfJg:butqgn2)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @weithegreat)

**Pull request merged**
