### PR TITLE
Move Jenkins files to external dirs

### PR DESCRIPTION
**Pull request by nicolecheetham**
Moves Jenkins github files and install prereqs to the external example directories

Issue: https://github.com/RobotLocomotion/drake-external-examples/issues/309

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322)

### CODE REVIEW

**Review by nicolecheetham — COMMENTED** [review]
+@BetsyMcPhail for feature review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-:-O8I84u53BHL0E4F0C8_:b-1dud86)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @nicolecheetham)

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-:-O8J4Cn5-nmxYXqxzvM3:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
+@xuchenhan-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-:-O8JDY_u8Gtfe5GMWEQW:b8rrdla)* status: all discussions resolved, LGTM missing from assignee xuchenhan-tri, platform LGTM from [betsymcphail] (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — CHANGES_REQUESTED** [review]
I should have been more specific. I pinned that question to specific locations related to Jenkins.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-:-O8JS39T5KBR_8VJDust:b273r59)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

___
*[`Jenkinsfile` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-O8JSFKPAvLpqTM4r8jC:-O8JSFKPAvLpqTM4r8jD:b-cgma5) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/af5ebb8845e2be44ab31f29f10d7604c5850ff62/Jenkinsfile#L28)):*
> ```Groovy
>         }
>       } catch (e) {
>         if (env.BRANCH_NAME == 'main') {
> ```

For example, do we have a way of confirming this is doing the right thing when a test fails?

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with a couple of questions.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-:-O8JWVXaBf6Eoxs1S6NX:beabcxg)* status: 2 unresolved discussions, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @nicolecheetham)

___
*[`drake_bazel_external/setup/ubuntu/install_prereqs` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-O8JUvxH7dwleWvJhpDp:-O8JUvxH7dwleWvJhpDq:bppvn3a) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/af5ebb8845e2be44ab31f29f10d7604c5850ff62/drake_bazel_external/setup/ubuntu/install_prereqs#L84)):*
> ```
> 
> apt-get update
> apt-get install --no-install-recommends $(cat <<EOF
> ```

BTW, where are we getting this list of prerequisites? It looks like some of these should already been installed by the Drake `install_prereqs` script?

**Review by nicolecheetham — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322)* status: 2 unresolved discussions, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @xuchenhan-tri)

___
*[`drake_bazel_external/setup/ubuntu/install_prereqs` line 84 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-O8JUvxH7dwleWvJhpDp:-O9BmNU_EhA0V8Y8ZXkN:b-d6ok1d) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/af5ebb8845e2be44ab31f29f10d7604c5850ff62/drake_bazel_external/setup/ubuntu/install_prereqs#L84)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, where are we getting this list of prerequisites? It looks like some of these should already been installed by the Drake `install_prereqs` script?
</blockquote></details>

My understanding is that these prerequisites have been slowly accumulated over time. And you are correct. Most are already installed via Drake's source prereqs or binary tar file. The goal of this PR is just to move the file to the ideal places. Afterwards, another PR will reduce the redundancy of these prerequisites. I hope this answers your questions.

**Review by BetsyMcPhail — COMMENTED** [review]
> Reviewed 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322)* status: 2 unresolved discussions, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @xuchenhan-tri)

___
*[`Jenkinsfile` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-O8JSFKPAvLpqTM4r8jC:-O9R9TPLACqVZmRfazir:b-l89vah) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/af5ebb8845e2be44ab31f29f10d7604c5850ff62/Jenkinsfile#L28)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

For example, do we have a way of confirming this is doing the right thing when a test fails?
</blockquote></details>

Good question, I temporarily introduced some errors to this PR to test it out.

Looking at https://drake-jenkins.csail.mit.edu/job/RobotLocomotion/job/drake-external-examples/job/PR-322/

- 12 has no errors
- 13 has a bazel error
- 14 has a cmake error

The other important thing to note is in 12 you can see the Bazel and CMake jobs running on different instances. From the console log:

Running on [EC2 (ec2-us-east-1) - drake-linux-jammy-unprovisioned-2024-09-03 (i-0e32d0c572399129a)](https://drake-jenkins.csail.mit.edu/computer/EC2%20%28ec2%2Dus%2Deast%2D1%29%20%2D%20drake%2Dlinux%2Djammy%2Dunprovisioned%2D2024%2D09%2D03%20%28i%2D0e32d0c572399129a%29/)

.....

Running on [EC2 (ec2-us-east-1) - drake-linux-jammy-unprovisioned-2024-09-03 (i-0b9053ece4b5a9751)](https://drake-jenkins.csail.mit.edu/computer/EC2%20%28ec2%2Dus%2Deast%2D1%29%20%2D%20drake%2Dlinux%2Djammy%2Dunprovisioned%2D2024%2D09%2D03%20%28i%2D0b9053ece4b5a9751%29/)

....

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322)* status: 2 unresolved discussions, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @xuchenhan-tri)

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-:-O9S0C3e7vQwOXHostXg:bnfp4nl)* status: 2 unresolved discussions, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — APPROVED** [review]
:lgtm: Sorry for the delay. I was OOO last week.

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-:-O9jz_gsDcEcAzVKtGMO:b48i5zg)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @nicolecheetham)

___
*[`Jenkinsfile` line 28 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/322#-O8JSFKPAvLpqTM4r8jC:-O9jzOhL3B5yMTcHRPnp:bf3vg7i) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/af5ebb8845e2be44ab31f29f10d7604c5850ff62/Jenkinsfile#L28)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

Good question, I temporarily introduced some errors to this PR to test it out.

Looking at https://drake-jenkins.csail.mit.edu/job/RobotLocomotion/job/drake-external-examples/job/PR-322/

- 12 has no errors
- 13 has a bazel error
- 14 has a cmake error

The other important thing to note is in 12 you can see the Bazel and CMake jobs running on different instances. From the console log:

Running on [EC2 (ec2-us-east-1) - drake-linux-jammy-unprovisioned-2024-09-03 (i-0e32d0c572399129a)](https://drake-jenkins.csail.mit.edu/computer/EC2%20%28ec2%2Dus%2Deast%2D1%29%20%2D%20drake%2Dlinux%2Djammy%2Dunprovisioned%2D2024%2D09%2D03%20%28i%2D0e32d0c572399129a%29/)

.....

Running on [EC2 (ec2-us-east-1) - drake-linux-jammy-unprovisioned-2024-09-03 (i-0b9053ece4b5a9751)](https://drake-jenkins.csail.mit.edu/computer/EC2%20%28ec2%2Dus%2Deast%2D1%29%20%2D%20drake%2Dlinux%2Djammy%2Dunprovisioned%2D2024%2D09%2D03%20%28i%2D0b9053ece4b5a9751%29/)

....
</blockquote></details>

Nice, thank you!

**Pull request merged**
