### PR TITLE
Change default branch to main

### PR DESCRIPTION
**Pull request by jamiesnape**
Needs GitHub configuration change. Jenkins will re-index the default branch automatically.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/202)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/202)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jamiesnape and @jwnimmer-tri)

___
*[drake_cmake_installed/README.md, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/202#-MYezNzwE3ilaDKbRsFq:-MYezNzwE3ilaDKbRsFr:b9rltvy) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/059f47a10420067e39ead3cec13e20908f6fa86d/drake_cmake_installed/README.md#L18)):*
> ```Markdown
> # (Optionally) Install GTest
> # You could also explicitly pull gtest into the CMake build directly:
> #     https://github.com/google/googletest/tree/HEAD/googletest
> ```

_Meta_ For all of the below...

If other projects choose their nominal branch name as "master", I don't see why we have to route around that.  We should use upstream's preferred terminology when referring to upstream resources, even if we are choosing a different name for our own project..

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/202)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[drake_cmake_installed/README.md, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/202#-MYezNzwE3ilaDKbRsFq:-MYf-6QB7nlVmmBgrZxv:b-6whpva) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/059f47a10420067e39ead3cec13e20908f6fa86d/drake_cmake_installed/README.md#L18)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

_Meta_ For all of the below...

If other projects choose their nominal branch name as "master", I don't see why we have to route around that.  We should use upstream's preferred terminology when referring to upstream resources, even if we are choosing a different name for our own project..
</blockquote></details>

My feeling is that it is going to be "when" rather than "if" master changes to main (especially with respect to Google) and this URL works both ways and is not incorrect if he desire is to refer to the latest version..

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/202)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[drake_cmake_installed/README.md, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/202#-MYezNzwE3ilaDKbRsFq:-MYf18TU8Q0hdbSTMZkN:b1xvk7w) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/059f47a10420067e39ead3cec13e20908f6fa86d/drake_cmake_installed/README.md#L18)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

My feeling is that it is going to be "when" rather than "if" master changes to main (especially with respect to Google) and this URL works both ways and is not incorrect if he desire is to refer to the latest version..
</blockquote></details>

But anyway, I reverted it for ROS and the vendored file.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/202)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jamiesnape and @jwnimmer-tri)

___
*[drake_cmake_installed/README.md, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/202#-MYezNzwE3ilaDKbRsFq:-MYf3nmC8KEGT6q_9D7e:bnr3zja) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/059f47a10420067e39ead3cec13e20908f6fa86d/drake_cmake_installed/README.md#L18)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

But anyway, I reverted it for ROS and the vendored file.
</blockquote></details>

Even if they rename their branch, `master` will http redirect to `main` through the magic of github, so there is no need to respell it here.  The new HEAD spelling changes the git drop-down picker on the served page to some weird (current) hash, instead of the more obvious "master".

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/202#-:-MYf6K3jArqRzZRwi9Pr:bnfp4nl)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @jamiesnape)

___
*[drake_cmake_installed/README.md, line 18 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/202#-MYezNzwE3ilaDKbRsFq:-MYf65OVBmf18rYIHMOS:btlk9s0) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/059f47a10420067e39ead3cec13e20908f6fa86d/drake_cmake_installed/README.md#L18)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

git will actually crash and burn, but if you feel that strongly...
</blockquote></details>

This is a web browser URI that explains the CMake build instructions.  It's not something usable for git clone.

**Pull request merged**
