### PR TITLE
Ensure Bazel gpg public key is updated

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/229)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
Follows workaround from https://github.com/bazelbuild/bazel/issues/15558

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/229#-:-N2s-9PJ9rris7NPONS-:b-vzokkk)* status: all discussions resolved, platform LGTM missing

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri would you like to review this or is there someone else I can assign?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/229#-:-N2s-VUl5hbBZGGKWGo7:bk3erq2)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I'm about to be out for the day.  Maybe @svenevs tomorrow morning?

**Review by BetsyMcPhail — COMMENTED** [review]
Sounds good to me.

-@jwnimmer-tri 
+@svenevs for review please 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/229#-:-N2s0zj_3WLNUPhdeG_o:b-duks3z)* status: all discussions resolved, LGTM missing from assignee svenevs, platform LGTM missing (waiting on @svenevs)

**Review by svenevs — APPROVED** [review]
:lgtm:, tested installation script in a docker container as well and it is successful.

I opened #230 to remind us that ideally we can switch back at some point.  I will merge this now though for the nightlies to hopefully succeed again.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/229#-:-N2sdJKJBoZVsiarhdcz:be88kzx)* status: all discussions resolved, platform LGTM missing (waiting on @BetsyMcPhail)

**Review by svenevs — APPROVED** [review]
> I will merge this now though for the nightlies to hopefully succeed again.

Whoops.  This repo needs two reviewers.

+@sherm1 for platform review (Wednesday) per schedule please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/229#-:-N2sddWJCZN3gNuRpcqR:b-ux9ng4)* status: all discussions resolved, LGTM missing from assignee sherm1, platform LGTM missing (waiting on @sherm1)

**Comment by BetsyMcPhail** [comment]
The nightly build is passing again without this change. I'm going to close this, we can open back up if needed.

**Pull request closed without merging**
