### PR TITLE
Move GHA prereqs to examples and refactor

### PR DESCRIPTION
**Pull request by nicolecheetham**
* Moves the binary install prereqs to the necessary example directories
* Removes unnecessary dependencies within each version of the GHA prereqs

Issue: https://github.com/RobotLocomotion/drake-external-examples/issues/309

Issue: https://github.com/RobotLocomotion/drake-external-examples/issues/61

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
FYI The setup scripts in each project like `drake_cmake_installed/setup/foo` should not be hard-coding their subdir name like `drake_cmake_installed` anywhere inside the script.  When the users makes their own repo, that name will no longer match.  The code that calls those scripts should `chdir` to the correct relative path (the subdir, not the git repository root) before calling anything.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail and @nicolecheetham)

___
*[`drake_ament_cmake_installed/.github/ros_humble_setup` line 11 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8dDD6cDKlfzZ2ZES3L:-O8dDD6cDKlfzZ2ZES3M:bk221gx) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/c9a71fd6ce45f28db471cbc95eb9d6bc276edcf9/drake_ament_cmake_installed/.github/ros_humble_setup#L11)):*
> ```
> export DEBIAN_FRONTEND='noninteractive'
> 
> cd "$(dirname "${BASH_SOURCE}")"
> ```

BTW I imagine all of these CI scripts would be easier to understand if the chdir had the `..` part on it, instead of tacking it into the below:

```sh
cd $(dirname "${BASH_SOURCE}")/..
setup/ros_humble/binary_install_prereqs --ros-humble
```
___
*[`drake_bazel_download/setup/ubuntu/binary_install_prereqs` line 3 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8dEqGNB8XyeayVlEJI:-O8dEqGNB8XyeayVlEJJ:b-j9w41u) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/c9a71fd6ce45f28db471cbc95eb9d6bc276edcf9/drake_bazel_download/setup/ubuntu/binary_install_prereqs#L3)):*
> ```
> #!/bin/bash
> 
> # Copyright (c) 2020, Massachusetts Institute of Technology.
> ```

Working

These files being copied now (coming from `scripts/setup/linux/ubuntu/jammy`) are the last remnants of the license text spam we're trying to get rid of in DEE.

Give me a little time to see if there is any way we can avoid copying this spam, before we make it worse with this PR.
___
*[`drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8dEHYd3w2pKjx2AQv2:-O8dEHYd3w2pKjx2AQv3:b-mwcjas) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/c9a71fd6ce45f28db471cbc95eb9d6bc276edcf9/drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs#L1)):*
> ```
> #!/bin/bash
> ```

BTW What if the name of this script was always `setup/install_prereqs` instead of `setup/ros_humble/binary_install_prereqs`.

Drake's upstream setup logic at https://github.com/RobotLocomotion/drake/tree/master/setup is quite complicated so it split into subdirs & etc, but for these examples our goal is to keep it simple, so having extra directory nesting seems contrary to the goal?

Using a simple, uniform name, also lets us keep the file_sync_test intact.

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 5 of 9 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @jwnimmer-tri and @nicolecheetham)

___
*[`drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs` line 72 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8gnCxpAysvH28I3Nsu:-O8gnCxpAysvH28I3Nsv:b-h2tt6t) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/d6327fc16f7e4a008dbe922c6981c048f95a6dd2/drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs#L72)):*
> ```
> tar -xf drake.tar.gz -C /opt
> 
> # Show version for debugging; use echo for newline / readability.
> ```

BTW I'm not sure if this should be removed? It's perhaps useful to show the drake version in the output?

**Review by nicolecheetham — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail and @jwnimmer-tri)

___
*[`drake_ament_cmake_installed/.github/ros_humble_setup` line 11 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8dDD6cDKlfzZ2ZES3L:-O8m1k0fCXQ9Dh6tszQL:b-wwrwl4) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/c9a71fd6ce45f28db471cbc95eb9d6bc276edcf9/drake_ament_cmake_installed/.github/ros_humble_setup#L11)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW I imagine all of these CI scripts would be easier to understand if the chdir had the `..` part on it, instead of tacking it into the below:

```sh
cd $(dirname "${BASH_SOURCE}")/..
setup/ros_humble/binary_install_prereqs --ros-humble
```
</blockquote></details>

I agree. I will change it.
___
*[`drake_bazel_download/setup/ubuntu/binary_install_prereqs` line 3 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8dEqGNB8XyeayVlEJI:-O8m1eLT4WCNjCSa-p9a:b-837i3v) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/c9a71fd6ce45f28db471cbc95eb9d6bc276edcf9/drake_bazel_download/setup/ubuntu/binary_install_prereqs#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

These files being copied now (coming from `scripts/setup/linux/ubuntu/jammy`) are the last remnants of the license text spam we're trying to get rid of in DEE.

Give me a little time to see if there is any way we can avoid copying this spam, before we make it worse with this PR.
</blockquote></details>

Okay.
___
*[`drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8dEHYd3w2pKjx2AQv2:-O8lxxxy6KdJ78SxxlP9:b2txja5) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/c9a71fd6ce45f28db471cbc95eb9d6bc276edcf9/drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW What if the name of this script was always `setup/install_prereqs` instead of `setup/ros_humble/binary_install_prereqs`.

Drake's upstream setup logic at https://github.com/RobotLocomotion/drake/tree/master/setup is quite complicated so it split into subdirs & etc, but for these examples our goal is to keep it simple, so having extra directory nesting seems contrary to the goal?

Using a simple, uniform name, also lets us keep the file_sync_test intact.
</blockquote></details>

That could be possible. The one exception is drake_cmake_installed as the mac and ubuntu install_prereqs need to be distinguished from one another. This can be done with subdirs. Another way is renaming the multiple install_prereqs of this example to mac_install_prereqs and ubuntu_install_prereqs. Is there an option that is preferrable to you? I'm also open to other ideas.
___
*[`drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs` line 72 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8gnCxpAysvH28I3Nsu:-O8m14zvBo1SiV-iWp3m:bdx553q) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/d6327fc16f7e4a008dbe922c6981c048f95a6dd2/drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs#L72)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

BTW I'm not sure if this should be removed? It's perhaps useful to show the drake version in the output?
</blockquote></details>

I can add it back. It doesn't hurt to have something for debugging. Moreover, I was on the fence whether to remove it or not.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail and @nicolecheetham)

___
*[`drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8dEHYd3w2pKjx2AQv2:-O8m2dGg3en4jDYAS4i6:bxr6a4c) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/c9a71fd6ce45f28db471cbc95eb9d6bc276edcf9/drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs#L1)):*
<details><summary><i>Previously, nicolecheetham (Nicole C.) wrote…</i></summary><blockquote>

That could be possible. The one exception is drake_cmake_installed as the mac and ubuntu install_prereqs need to be distinguished from one another. This can be done with subdirs. Another way is renaming the multiple install_prereqs of this example to mac_install_prereqs and ubuntu_install_prereqs. Is there an option that is preferrable to you? I'm also open to other ideas.
</blockquote></details>

There is another option: just have one bash script called `install_prereqs`, but inside it has if-then-else blocks that check for which platform it's running on, and take different steps accordingly.  That makes the user README even more clear -- run one script, no matter which platform you are on.

**Review by nicolecheetham — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail and @jwnimmer-tri)

___
*[`drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8dEHYd3w2pKjx2AQv2:-O8m_UsS9TCKvDRCyILZ:br94722) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/c9a71fd6ce45f28db471cbc95eb9d6bc276edcf9/drake_ament_cmake_installed/setup/ros_humble/binary_install_prereqs#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is another option: just have one bash script called `install_prereqs`, but inside it has if-then-else blocks that check for which platform it's running on, and take different steps accordingly.  That makes the user README even more clear -- run one script, no matter which platform you are on.
</blockquote></details>

That is a good idea. I'll work on it.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 5 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail)

___
*[`drake_bazel_download/setup/ubuntu/binary_install_prereqs` line 3 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8dEqGNB8XyeayVlEJI:-O8sAD3oCBDoAoSE4bFI:b-kx9l59) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/c9a71fd6ce45f28db471cbc95eb9d6bc276edcf9/drake_bazel_download/setup/ubuntu/binary_install_prereqs#L3)):*
<details><summary><i>Previously, nicolecheetham (Nicole C.) wrote…</i></summary><blockquote>

Okay.
</blockquote></details>

Retracted.  Looking in more detail, yes I will be able to fix this, but it will be much easier after this PR moves the files around.  For now, copying them with this blob intact is good.

**Review by jwnimmer-tri — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail and @nicolecheetham)

___
*[`.github/workflows/ci.yml` line 70 at r5](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-O8wKogt1NaqHLfGmojn:-O8wKogu4T6RLlkL7XDJ:b-lnfutd) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/c1e93ab542ea2259fe6407856477b35e94c43042/.github/workflows/ci.yml#L70)):*
> ```YAML
>           pip3.11 --version
>       - name: setup
>         run: ./drake_cmake_installed/setup/install_prereqs --mac
> ```

The user should not need to pass a flag.  (If they did, we would need to document that in the README, but that's not ideal.)  The script itself can interrogate which OS it's running on, internally, and take the correct actions automatically.

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 8 of 9 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @nicolecheetham)

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321#-:-O9BK50z8DAb75NciREs:bnfp4nl)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM from [jwnimmer-tri] (waiting on @nicolecheetham)

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM from [jwnimmer-tri] (waiting on @nicolecheetham)

**Comment by jwnimmer-tri** [comment]
This is only waiting on an LGTM from @BetsyMcPhail.

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/321)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri, betsymcphail] (waiting on @nicolecheetham)

**Pull request merged**
