### PR TITLE
Simplify the drake_cmake_external example

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Updates to the CMakeLists include:
* Use the modern method of finding Python.
* Remove unnecessary subdirectory

This PR splits out the non-setup changes from #313, working towards #61

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/338)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@nicolecheetham for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/338#-:-OBb_nGt6sZMZdWcAlJg:b-y76idi)* status: all discussions resolved, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

**Review by nicolecheetham — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/338)* status: 2 unresolved discussions, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @BetsyMcPhail)

___
*[`drake_cmake_external/drake_external_examples/CMakeLists.txt` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/338#-OBf5nzx9M_blCa4SIAR:-OBf5nzx9M_blCa4SIAS:b2ck4f3) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/b01ab48c895b51c9c40dd215d5f281a01b41e80e/drake_cmake_external/drake_external_examples/CMakeLists.txt#L18)):*
> ```CMake
> 
> get_filename_component(PYTHONPATH
>   "${drake_DIR}/../../python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/site-packages"
> ```

The Jenkins job failed. It seems one of the import_all_test.py tests was not able to run as it was unable to find the executable. I think keeping the get_filename_component command should resolve this. If you know another way that is fine too.
___
*[`drake_cmake_external/drake_external_examples/CMakeLists.txt` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/338#-OBf4muK80eBDJRCmzWS:-OBf4muL1HiCTeGVQE3m:b-ib4rjp) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/7b8418847a609aa9630be836c621259ed2df0770/drake_cmake_external/drake_external_examples/CMakeLists.txt#L6)):*
> ```CMake
> project(drake_external_examples)
> 
> find_package(Python3 REQUIRED COMPONENTS Interpreter Development)
> ```

I believe after Python3 you would need to put ${drake_PYTHON_VERSION} EXACT like that of the drake_cmake_installed CML.

**Review by BetsyMcPhail — COMMENTED** [review]
@nicolecheetham this is ready for another look

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/338#-:-OBgauH89GhHX5fQ7y5F:b-d22tss)* status: 2 unresolved discussions, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

___
*[`drake_cmake_external/drake_external_examples/CMakeLists.txt` line 6 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/338#-OBf4muK80eBDJRCmzWS:-OBgaLcx6JtcGLS7suAY:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/7b8418847a609aa9630be836c621259ed2df0770/drake_cmake_external/drake_external_examples/CMakeLists.txt#L6)):*
<details><summary><i>Previously, nicolecheetham (Nicole C.) wrote…</i></summary><blockquote>

I believe after Python3 you would need to put ${drake_PYTHON_VERSION} EXACT like that of the drake_cmake_installed CML.
</blockquote></details>

Done.
___
*[`drake_cmake_external/drake_external_examples/CMakeLists.txt` line 18 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/338#-OBf5nzx9M_blCa4SIAR:-OBgaPMF9sdXVrE7rHE2:be0xpo5) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/b01ab48c895b51c9c40dd215d5f281a01b41e80e/drake_cmake_external/drake_external_examples/CMakeLists.txt#L18)):*
<details><summary><i>Previously, nicolecheetham (Nicole C.) wrote…</i></summary><blockquote>

The Jenkins job failed. It seems one of the import_all_test.py tests was not able to run as it was unable to find the executable. I think keeping the get_filename_component command should resolve this. If you know another way that is fine too.
</blockquote></details>

I had failed to update some Python-related variables, it is passing now.

**Review by nicolecheetham — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/338#-:-OBge2oU1qq90rVTLeqc:bnfp4nl)* status: all discussions resolved, platform LGTM missing

**Review by BetsyMcPhail — COMMENTED** [review]
+@rpoyner-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/338#-:-OC4BPp62Kxr0a8p7i4e:b-hnc6mz)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @nicolecheetham and @rpoyner-tri)

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/338#-:-OC4eMtnAoemylVTy5VE:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [rpoyner-tri] (waiting on @BetsyMcPhail)

**Pull request merged**
