### PR TITLE
Port from Focal to Jammy

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For the Jenkins step to pass, we'll need https://github.com/RobotLocomotion/drake/issues/21032 first.  Probably we should force-merge without that, and circle back later to make sure it's all working.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/281)

### CODE REVIEW

**Review by sherm1 — APPROVED** [review]
Platform :lgtm:, mostly rubber-stamp. I looked at spelling and the like which looks fine but I don't have a way to know if the right additions and deletions were made -- hopefully there is a competent feature reviewer out there who does know.

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/281#-:-NrNCmcDE9NNHR-ql8ca:b-79xmn8)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [sherm1] (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/281)* status: 1 unresolved discussion, platform LGTM from [sherm1] (waiting on @BetsyMcPhail and @sherm1)

___
*[`Jenkinsfile` line 5 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/281#-NrajM8388jJmHYP2P2J:-NrbGzdX7ZoB3zABO1gE:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/e3838a4a1832b63f3fde91708a9ecc477ac153ab/Jenkinsfile#L5)):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

To use the standard jammy unprovisioned image, change to `linux-jammy-unprovisioned`. A test run with this passed: https://drake-jenkins.csail.mit.edu/job/RobotLocomotion/job/drake-external-examples/job/PR-282/2/
</blockquote></details>

Done.

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/281#-:-NrbJk12E-xN6pGV-jCh:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [sherm1, betsymcphail] (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Slow jenkins is slow, but it eventually passed!

**Pull request merged**
