### PR TITLE
Remove PCL example

### PR DESCRIPTION
**Pull request by jamiesnape**
Broken on macOS and was maybe a little out of place here anyway.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/179)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for review (or anyone else who drives by).

**Comment by jamiesnape** [comment]
I do not really know what purpose the example serves or why PCL in particular deserves a compatibility example. It is an aging, heavyweight dependency whose build system already needs to be patched to actually work, so it already is not a good example of best practice use of the Drake build system.  It is also an outlier. We transcribe almost everything else from Drake, so the code just needs syncing. The novel content in this repo is supposed to be the various sets of build files.

**Comment by jwnimmer-tri** [comment]
The other problem with the PCL example is that nobody is maintaining it.

The PCL example came about in the days of Ubuntu 16.04, where there were actually tricky questions around eigen and proj and how it all fits together on 16.04.  At least some (if not all) of those problems are resolved on Ubuntu 18.04, which is our minimum supported version now.  The README even disclaims 18.04 support(?!).

This was underlined by the fact that when CI broke, there is nobody on the hook to resolve the regression, because nobody cars about or has ownership over this folder.

For all of the above, I support "git remembers" on this folder.  If someone wants to step up and rewrite it for bionic, focal, and macOS (+ promising to fix defects as things break), they are free to re-submit.

In any case, we need to do something ASAP because CI is broken and that is "priority: emergency".

**Comment by EricCousineau-TRI** [comment]
OK SGTM in terms of maintenance.

**Pull request merged**
