### PR TITLE
Add drake_cmake_installed_apt example

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates RobotLocomotion/drake#12783. I wanted a direct analog of the C++ particles example for Python that I would ideally propagate to the other projects, so that is added here, but would need to be upstreamed (first). Otherwise, I guess I grab one of the toy examples elsewhere in this repo, but they are very limited IMO.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/203)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Depends on RobotLocomotion/drake#15016.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review (or at least an initial pass to see if you like the idea of a Python particles example).

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 16 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/203#-:-M_aov5-5PrBIAdAF76E:bnfp4nl)* status: 3 unresolved discussions, platform LGTM from [jwnimmer-tri] (waiting on @jamiesnape)

___
*[drake_cmake_installed_apt/.gitignore, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/203#-M_anhRs3H9HPlMl8xpn:-M_anhRs3H9HPlMl8xpo:bjr1li6) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/db48057fa123a6e09b3ddcb1215081608b6aa88e/drake_cmake_installed_apt/.gitignore#L1)):*
> ```ignore
> /.idea/
> ```

nit The other examples' gitignores for have copyright boilerplate.  Should this one also?
___
*[drake_cmake_installed_apt/.gitignore, line 3 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/203#-M_ancTw7yzU63TGMja2:-M_ancTw7yzU63TGMja3:b-pehfow) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/db48057fa123a6e09b3ddcb1215081608b6aa88e/drake_cmake_installed_apt/.gitignore#L3)):*
> ```ignore
> /.idea/
> /build/
> /cmake-build-*/
> ```

nit The leading `/` here seems better, but the other `drake_cmake_...` examples don't have it (nor do they use this glob).  Make them consistent with this one?
___
*[drake_cmake_installed_apt/CMakeLists.txt, line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/203#-M_R7fwc9sNS81MsQwQR:-M_R7fwdDBbAtgTlKsu8:bxbsany) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/db48057fa123a6e09b3ddcb1215081608b6aa88e/drake_cmake_installed_apt/CMakeLists.txt#L45)):*
> ```CMake
> find_package(Threads MODULE REQUIRED)
> 
> add_library(gtest STATIC
> ```

I originally was going to post this:

    I see that `drake_cmake_installed` already vendors gtest, so
    this is replicating that approach -- but for an apt example,
    I'm curious why we use a vendored copy instead of the one
    from Ubuntu?

but after digging around some reference material, it does appear that (at least on Ubuntu 18.04), vendoring gtest is actually the accepted best practice, given the more rudimentary external project macros available with CMake 3.10.  Or at least, it's the best way to do it when you don't want to "sudo make install" :gasp:, which is the other option.
___
*[drake_cmake_installed_apt/README.md, line 5 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/203#-M_ajQGdAS2LXUwfr_Fg:-M_ajQGeEXG27KgNbjNy:bjiin79) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/db48057fa123a6e09b3ddcb1215081608b6aa88e/drake_cmake_installed_apt/README.md#L5)):*
> ```Markdown
> This example uses the [`cmake`](https://cmake.org/) build system with an
> instance of Drake installed using the
> [APT](http://manpages.ubuntu.com/manpages/bionic/man8/apt.8.html) package
> ```

nit Prefer "https"

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/203)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @jwnimmer-tri)

___
*[drake_cmake_installed_apt/CMakeLists.txt, line 45 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/203#-M_R7fwc9sNS81MsQwQR:-M_bR4xC9dCOYLfEp8EI:b5lezz5) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/db48057fa123a6e09b3ddcb1215081608b6aa88e/drake_cmake_installed_apt/CMakeLists.txt#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I originally was going to post this:

    I see that `drake_cmake_installed` already vendors gtest, so
    this is replicating that approach -- but for an apt example,
    I'm curious why we use a vendored copy instead of the one
    from Ubuntu?

but after digging around some reference material, it does appear that (at least on Ubuntu 18.04), vendoring gtest is actually the accepted best practice, given the more rudimentary external project macros available with CMake 3.10.  Or at least, it's the best way to do it when you don't want to "sudo make install" :gasp:, which is the other option.
</blockquote></details>

Yes, for some reason, when Google said do not provide system-wide GTest binaries the whole world jumped (`libgtest-dev` pre-20.04 is unusually just providing source code). At least everyone (including Google, but most people did not notice) eventually came to their senses (in Focal and Homebrew as of last year) and treat it like any other C++ library.

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/203)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @jamiesnape)

**Pull request merged**
