### PR TITLE
Remove support for Ubuntu 18 (Bionic)

### LINKED ISSUE #219: Upgrade CI testing to use Ubuntu 20 (focal)
Drake's support for Ubuntu 18 is deprecated will be retired soon (https://github.com/RobotLocomotion/drake/issues/13391).

Given that, we should ensure that all of the `drake-external-examples` tests are being run on Focal.  We could imagine running on both Bionic and Focal for the next month, but to save some effort it's probably just worth moving to Focal wholesale.

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Resolves #219

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/222)

### CODE REVIEW

**Comment by BetsyMcPhail** [comment]
Jenkins PR build: https://drake-jenkins.csail.mit.edu/job/RobotLocomotion/job/drake-external-examples/view/change-requests/job/PR-222/

**Review by BetsyMcPhail — COMMENTED** [review]
Issue #214 gave a good hint to the failures. `drake_bazel_installed` uses the bionic nightly packages by default, and therefore, in the tests.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/222#-:-Mxtw6Qt6r2-I2-UXfVR:bn7iqeb)* status: all discussions resolved, platform LGTM missing

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for review please. This PR goes further than described in the issue and removes all support for Bionic.  The final commit can be split off and saved until April if you prefer.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/222#-:-Mxu12Xl746zrrjiLYjb:b-qu0siq)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
I think a total purge of Bionic is correct.  I'll review the non-ROS parts of this.

+@EricCousineau-TRI for review of the ament- and catkin-related changes, please.

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm: on my parts.

> Reviewed 14 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/222#-:-Mxu7EU99wsrRwN7BnRA:b-lodf4g)* status: 1 unresolved discussion, LGTM missing from assignee ericcousineau-tri, platform LGTM from [jwnimmer-tri] (waiting on @BetsyMcPhail, @EricCousineau-TRI, and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/222#-Mxu4m2sAJTtwOfJWn9w:-Mxu4m2t7aX3MMf8OlmW:b-pa96lh) (no related file):*
nit The top-level README.md in this repo says "Not all example projects are supported on macOS or Ubuntu 20.04 (Focal Fossa)." which probably inaccurate now?

---

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/222)* status: 1 unresolved discussion, LGTM missing from assignee ericcousineau-tri, platform LGTM from [jwnimmer-tri] (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/222#-Mxu4m2sAJTtwOfJWn9w:-Mxu8TTgAsjoypPSLTCd:bsy6f9s) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit The top-level README.md in this repo says "Not all example projects are supported on macOS or Ubuntu 20.04 (Focal Fossa)." which probably inaccurate now?
</blockquote></details>

Good catch. I'm not sure if was actually ever true. It certainly shouldn't be now.

---

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/222)* status: all discussions resolved, LGTM missing from assignee ericcousineau-tri, platform LGTM from [jwnimmer-tri] (waiting on @EricCousineau-TRI and @jwnimmer-tri)

**Review by EricCousineau-TRI — APPROVED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/222)* status: all discussions resolved, LGTM missing from assignee ericcousineau-tri, platform LGTM from [jwnimmer-tri] (waiting on @BetsyMcPhail)

___
*[.github/workflows/ci.yml, line 55 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/222#-MxuQm9F0e-iSiWSS6Fm:-MxuQm9F0e-iSiWSS6Fn:b-dur7l8) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/68eda081269eb471fbbe9d1876965a3e19160a99/.github/workflows/ci.yml#L55)):*
> ```YAML
>         shell: zsh -efuo pipefail {0}
>   ros_foxy:
>     name: ros 2 foxy
> ```

BTW Latest support is for Galactic:
https://docs.ros.org/en/galactic/Installation.html
FYI @iantheengineer Once we have ROS 2 / Anzu integration underway, we should add that here.

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm: for ament- and catkin-related changes - thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/222#-:-MxuRouo8GnzD76re7bV:b-lw65mz)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, ericcousineau-tri] (waiting on @BetsyMcPhail)

**Pull request merged**
