### PR TITLE
CI setup clean-up

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #61 

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/304)

### CODE REVIEW

**Review by BetsyMcPhail — COMMENTED** [review]
+@nicolecheetham for review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/304#-:-O756_139Ty5rQ2xczZz:b-y76idi)* status: all discussions resolved, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

**Review by BetsyMcPhail — COMMENTED** [review]
Replaces #301 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/304#-:-O756l6q2YVJxW_E1Nt2:bhsh1cj)* status: all discussions resolved, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

**Review by BetsyMcPhail — COMMENTED** [review]
@nicolecheetham this is ready for another look. The changes are slightly different than we discussed, let me know what you think.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/304#-:-O79x3s522A6qME7dXF9:b-loiwuo)* status: all discussions resolved, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

**Review by nicolecheetham — APPROVED** [review]
:lgtm: I agree with all the changes. Also, I think we can further refactor the ubuntu_setup scripts but that can be another PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/304#-:-O7AIZn5EwjSE9If7br-:buiawv)* status: all discussions resolved, platform LGTM missing

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/304#-:-O7AXkrw2gU7NuRRrH4U:b1f7mq7)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri and @nicolecheetham)

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/304#-:-O7EgD26BKBEg8XAXMU2:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [jwnimmer-tri] (waiting on @BetsyMcPhail and @nicolecheetham)

___
*[`.github/workflows/ci.yml` line 70 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/304#-O7Ef9TM4m2MO9WGnieg:-O7Ef9TM4m2MO9WGnieh:bjva3fr) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/5bd749f4dd2c222775f88d885bc93d4a2fe61362/.github/workflows/ci.yml#L70)):*
> ```YAML
>           pip3.11 --version
>       - name: setup
>         run: ./scripts/setup/mac/install_prereqs
> ```

BTW Why isn't this script moved also?  It seems to me like it's of the same flavor as the other things being moved?  Maybe it's saved for a future PR?  BTW This script's neighboring `Brewfile` and `requirements.txt` are the kind of defects that #61 should solve.

**Review by jwnimmer-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/304)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @nicolecheetham)

___
*[`.github/workflows/ci.yml` line 70 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/304#-O7Ef9TM4m2MO9WGnieg:-O7EgMMt8erEa9sZvmXS:b6qqhmp) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/5bd749f4dd2c222775f88d885bc93d4a2fe61362/.github/workflows/ci.yml#L70)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Why isn't this script moved also?  It seems to me like it's of the same flavor as the other things being moved?  Maybe it's saved for a future PR?  BTW This script's neighboring `Brewfile` and `requirements.txt` are the kind of defects that #61 should solve.
</blockquote></details>

Oh, I see, this one isn't in `continuous_integration`, and we're keeping `scripts` for now.  Nevemind.

**Pull request merged**
