### PR TITLE
Run file_sync test in GHA CI

### LINKED ISSUE #308: Add GHA for private maintainer-only tests
In #307, I am adding a test case that helps us (as maintainer) ensure that files which are copied around inside of this repository all remain up-to-date and in sync.

After #307 merges, please add a new `.github/workflows/ci.yml` job which runs this test (by itself, not as part of any other existing build).

If you like, you could create a `private/test/run_all.sh` script for CI to call, in anticipation of us eventually adding more test programs.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Closes #308.

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/326)

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Well, the test [works](https://github.com/RobotLocomotion/drake-external-examples/actions/runs/11297872535/job/31425649161?pr=326)...

**Comment by mwoehlke-kitware** [comment]
Does the EOL fix need to be a separate PR?

**Review by BetsyMcPhail — APPROVED** [review]
I'm fine with it as part of this PR
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/326#-:-O8x0XlGEbhuCXq55LAs:b5jkl5x)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail] (waiting on @mwoehlke-kitware)

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/326)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail] (waiting on @mwoehlke-kitware)

**Pull request merged**
