### PR TITLE
drake_cmake_installed: Address upstream's -fvisibility settings

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Towards RobotLocomotion/drake#14047

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/187)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jamiesnape for review, please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/187#-:-MGxTXCaD26-dDSObgGh:bvcvgga)* status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing (waiting on @jamiesnape)

**Review by jamiesnape — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/187#-:-MGxcNIa498vhuO7pjLG:bg7igkv)* status: 1 unresolved discussion, platform LGTM from [jamiesnape] (waiting on @EricCousineau-TRI)

___
*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/187#-MGxbaoC5TGi6tI_Sm7e:-MGxbaoC5TGi6tI_Sm7f:b-om1hs8) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/7345f6436a6e04b4a3ef50d3dc2945ae6351d8eb/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L42)):*
> ```CMake
> # setting.
> # For more information, see:
> # https://github.com/RobotLocomotion/drake/issues/14047
> ```

Comment says why it is fine to set visibility to default, but does not say we must so do. Probably easier to add a few words than ask people to click and scroll down an issue.
___
*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/187#-MGxcGLA8e6WWMmf7bgj:-MGxcGLA8e6WWMmf7bgk:b5m2nf4) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/7345f6436a6e04b4a3ef50d3dc2945ae6351d8eb/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L43)):*
> ```CMake
> # For more information, see:
> # https://github.com/RobotLocomotion/drake/issues/14047
> set_target_properties(simple_bindings PROPERTIES CXX_VISIBILITY_PRESET "default")
> ```

BTW Do not need to quote `default`.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/187)* status: 1 unresolved discussion, platform LGTM from [jamiesnape] (waiting on @jamiesnape)

___
*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/187#-MGxbaoC5TGi6tI_Sm7e:-MGxd_KLBspEq8AcJFbn:b-tvi7jm) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/7345f6436a6e04b4a3ef50d3dc2945ae6351d8eb/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L42)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Comment says why it is fine to set visibility to default, but does not say we must so do. Probably easier to add a few words than ask people to click and scroll down an issue.
</blockquote></details>

Done. Thanks! (also changed to upstream issue)
___
*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/187#-MGxcGLA8e6WWMmf7bgj:-MGxdVcf33IEWWoUUsSL:b6xsp4j) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/7345f6436a6e04b4a3ef50d3dc2945ae6351d8eb/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L43)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Do not need to quote `default`.
</blockquote></details>

OK FWIW I hate CMake's shell-like syntax :( But yeah, sure, removed it.

**Review by jamiesnape — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/187)* status: :shipit: complete! all discussions resolved, platform LGTM from [jamiesnape]

**Comment by EricCousineau-TRI** [comment]
Oops... accidental squash :facepalm:

**Pull request merged**
