### PR TITLE
Split each example into its own Github action

### PR DESCRIPTION
**Pull request by BetsyMcPhail**
Towards #61 

This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306)

### CODE REVIEW

**Review by nicolecheetham — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306)* status: 1 unresolved discussion, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @BetsyMcPhail)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306#-O75cMQL-nxZ8OSgkLJX):*
I agree. The job names could be clearer. One suggestion is to move the job names after "ubuntu 22.04 jammy". This would help people see what OS is running for each job. Additionally, all prefix instances of "drake" can be removed in the name sections of the GHA. This is for DEE so it's already acknowledged that it will be used for drake. You could further remove instances of "download/installed" in the name sections. Though with this change, one would just need to properly distinguish the Jenkinsfile jobs with {cmake,bazel}_external. I think these changes can make the names more manageable and easier to read. I hope these suggestions helped. Besides the name clarity, the PR looks good

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306)* status: 1 unresolved discussion, LGTM missing from assignee nicolecheetham, platform LGTM missing (waiting on @nicolecheetham)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306#-O75cMQL-nxZ8OSgkLJX):*
<details><summary><i>Previously, nicolecheetham (Nicole C.) wrote…</i></summary><blockquote>

I agree. The job names could be clearer. One suggestion is to move the job names after "ubuntu 22.04 jammy". This would help people see what OS is running for each job. Additionally, all prefix instances of "drake" can be removed in the name sections of the GHA. This is for DEE so it's already acknowledged that it will be used for drake. You could further remove instances of "download/installed" in the name sections. Though with this change, one would just need to properly distinguish the Jenkinsfile jobs with {cmake,bazel}_external. I think these changes can make the names more manageable and easier to read. I hope these suggestions helped. Besides the name clarity, the PR looks good
</blockquote></details>

Thanks for the suggestions. It seems better now, I'm trying to be concise while still making it obvious which example is being tested.

**Review by nicolecheetham — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306#-:-O75vA-CApMNUJmtlHGi:bnfp4nl)* status: all discussions resolved, platform LGTM missing

**Review by BetsyMcPhail — COMMENTED** [review]
+@jwnimmer-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306#-:-O79elDv7wN0fhkA1z_i:b1f7mq7)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri and @nicolecheetham)

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm: moving in the right direction.  Just a couple of consistency nits to tidy up.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306#-:-O7A3mg-5AhLhETOk1rF:b-jjsize)* status: 3 unresolved discussions, platform LGTM from [jwnimmer-tri] (waiting on @BetsyMcPhail and @nicolecheetham)

___
*[`.github/workflows/ci.yml` line 20 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306#-O7A3Kyz09RlKtROZaBQ:-O7A3Kyz09RlKtROZaBR:b-qlados) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/ff08400ff3f64e789df6204f202275fe947cfe34/.github/workflows/ci.yml#L20)):*
> ```YAML
>   cancel-in-progress: true
> jobs:
>   macos_sonoma_arm:
> ```

nit This identifier should receive the same treatment as the rest of this PR -- adding the detail of which example it's running (in this case, `macos_sonoma_arm_cmake_installed`).
___
*[`.github/workflows/ci.yml` line 76 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306#-O7A2xta5BYeOnaaHOdD:-O7A2xtbCpRQMEynRdp9:b-r6tklr) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/ff08400ff3f64e789df6204f202275fe947cfe34/.github/workflows/ci.yml#L76)):*
> ```YAML
>         shell: zsh -efuo pipefail {0}
>   ros_humble:
>     name: ros 2 humble
> ```

nit Both this identifier on the prior line and this `name` should receive the same treatment (adding the detail of which example it's running)
___
*[`.github/workflows/ci.yml` line 128 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306#-O7A38Uf6Jtk1FCP9_zP:-O7A38Uf6Jtk1FCP9_zQ:b-r6tklr) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/ff08400ff3f64e789df6204f202275fe947cfe34/.github/workflows/ci.yml#L128)):*
> ```YAML
>         shell: bash
>   ubuntu_jammy_apt:
>     name: ubuntu 22.04 jammy apt
> ```

nit Both this identifier on the prior line and this `name` should receive the same treatment (adding the detail of which example it's running)

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/306)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @BetsyMcPhail)

**Pull request merged**
