### PR TITLE
Update github macos setup for drake prereqs

### PR DESCRIPTION
**Pull request by nicolecheetham**
Simplifying DEE approach of installing drake prereqs for macOS

Issue: https://github.com/RobotLocomotion/drake-external-examples/issues/61

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297)

### CODE REVIEW

**Review by nicolecheetham — COMMENTED** [review]
+@BetsyMcPhail for feature review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297#-:-O6NQVae1P5DOR4xsA0V:bj8rs74)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm: assuming that CI passes

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297#-:-O6S0AnA242ajrpDog_8:b43c03s)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
+@xuchenhan-tri for platform review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297#-:-O6S1Lnr8cMnaLeq8JGM:b-he5s78)* status: all discussions resolved, LGTM missing from assignee xuchenhan-tri, platform LGTM from [betsymcphail] (waiting on @xuchenhan-tri)

**Review by xuchenhan-tri — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

___
*[`scripts/setup/mac/install_prereqs` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297#-O6SY41Z0ZtPU1lQWg-h:-O6SY41Z0ZtPU1lQWg-i:b-usghn) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/11ab303593668df07211d93b2a44115930e68193/scripts/setup/mac/install_prereqs#L7)):*
> ```
> 
> # Installs a /usr/local/bin/bazel symlink that conflicts with that installed by
> # the bazel formula in Homebrew.
> ```

BTW, the comment here seems to be incompatible with the code below. Am I just not getting it?



_Code quote:_
```
# Installs a /usr/local/bin/bazel symlink that conflicts with that installed by
# the bazel formula in Homebrew.
```

**Review by xuchenhan-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297#-:-O6SYH946SbhGhOST833:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @BetsyMcPhail and @xuchenhan-tri)

___
*[`scripts/setup/mac/install_prereqs` line 7 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297#-O6SY41Z0ZtPU1lQWg-h:-O6X-_eW9F8R7VvSTvFz:brv20l6) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/11ab303593668df07211d93b2a44115930e68193/scripts/setup/mac/install_prereqs#L7)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, the comment here seems to be incompatible with the code below. Am I just not getting it?
</blockquote></details>

You are correct. The comment is supposed to start with "Uninstalls" as to properly describe the code below. I have updated so this is the case.

**Review by xuchenhan-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @nicolecheetham)

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @nicolecheetham)

**Review by BetsyMcPhail — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @nicolecheetham)

**Review by BetsyMcPhail — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/297)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, xuchenhan-tri] (waiting on @nicolecheetham)

**Pull request merged**
