### PR TITLE
Fix gflags imported target for Ubuntu

### PR DESCRIPTION
**Pull request by jamiesnape**
Most likely requires RobotLocomotion/drake#12250.

----
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/146)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Still failing :(
```
CMake Error at src/particles/CMakeLists.txt:40 (find_package):
  Could not find a package configuration file provided by "gflags" with any
  of the following names:

    gflagsConfig.cmake
    gflags-config.cmake
```

**Comment by jamiesnape** [comment]
> Still failing :(
> 
> ```
> CMake Error at src/particles/CMakeLists.txt:40 (find_package):
>   Could not find a package configuration file provided by "gflags" with any
>   of the following names:
> 
>     gflagsConfig.cmake
>     gflags-config.cmake
> ```

That one, I can fix. We need to switch CircleCI to Bionic.

**Comment by jamiesnape** [comment]
> CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Could NOT find Bazel: Found unsuitable version "1.0.1", but required is at
>   least "1.1" (found /usr/bin/bazel)

This one is a strange one. There must be a problem with the Bazel `apt` repo. I guess we have to manually download the `.deb` and lose our canary for future Bazel issues (for now).

**Comment by EricCousineau-TRI** [comment]
Aye, gotcha.

And for using Bionic, is just switching this line?
https://github.com/RobotLocomotion/drake-external-examples/blob/a37f16d0702a8ff6d0de43924ae50f9bb04be517/.circleci/config.yml#L36

**Comment by jamiesnape** [comment]
This one also
https://github.com/RobotLocomotion/drake-external-examples/blob/a37f16d0702a8ff6d0de43924ae50f9bb04be517/scripts/continuous_integration/circle_ci/setup#L34

and obviously we can delete the `xenial` folder completely.

**Comment by EricCousineau-TRI** [comment]
K, I'll make that PR.

**Comment by jamiesnape** [comment]
I forced a rebuild of the drake binaries, and it looks like this PR is going to pass on Linux, so I think we are good now.

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for review

**Pull request merged**
