### PR TITLE
Switch license to MIT-0

### LINKED ISSUE #240: Re-license to MIT-0
I'm considering re-licensing this repository to use the [MIT-0](https://opensource.org/licenses/MIT-0) license, so that when a Drake user copies those files to their own project in order to bootstrap their build system, they are free to remove Drake's license boilerplate from their forked copy.

As it stands today, anyone using this repository to bootstrap their own code probably needs to keep the entire BSD-3-Clause boilerplate in every file they copy from here.  They would only be exempt in case of files where copyright does not attach, e.g., the nearly-empty `.bazelproject` file.

I think attribution is a fine goal, but probably not necessary for the build system boilerplate here, and in any case they will still be in-effect "citing" Drake by using it as an external.

I've started a poll on slack to collect opinions about this, but I'm also open to hearing feedback here.

It looks like TRI owns the copyright to everything except #106 and #181.  We would need to ask those two authors to bless the new license prior to any change.  (Maybe copyright wouldn't attach to #106 but we should ask anyway as a courtesy.)

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Closes #240.

Relates to https://github.com/RobotLocomotion/drake/issues/1805 a bit.

- - -
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Hello @yf225, @cjds, and @adeeb10abbas.  Thank you for your past contributions to the `drake-external-examples` project (#106, #181, and #244)!

To make it easier for Drake's users to take advantage of these examples, I'd like to re-license this repository from the [BSD-3-Clause](https://opensource.org/licenses/BSD-3-Clause) license to the [MIT-0](https://opensource.org/licenses/MIT-0) license.  With the old license, users are required to preserve the examples' copyright notices in their own project, leading to a extra boilerplate and hassle.  With the new license, users would not be required to copy over those comments when bootstrapping their build system.

As past contributors to this repository, I'm seeking your approval of this license change.  Kindly please reply to this pull request, stating whether or not you approve of this change.  Your approval would effectively re-license your contribution under the new terms.

**Comment by adeeb10abbas** [comment]
@jwnimmer-tri sounds good to me! Happy to help/contribute :)

**Comment by yf225** [comment]
Sounds good to me too, thanks!

**Comment by jwnimmer-tri** [comment]
I went back through the @cjds contribution and it was only https://github.com/RobotLocomotion/drake-external-examples/commit/95a34660d85c2a3c2788c4866da63badfb238eff.

I'll check whether or not any copyright there has bled into other files, and for now plan to switch everything _except_ that contribution to MIT-0.

**Review by sherm1 — APPROVED** [review]
SPDX is lovely! However the changes here seem contrary to the instructions [here](https://spdx.dev/ids/):


Is that intentional?

Also in some but not all cases the vi directives preceding the copyright block were also deleted. I think I marked them all. Feel free to ignore if that was intentional.

> Reviewed 2 of 110 files at r1, 110 of 110 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-:-NSMaVWRDje0D57f9q83:b-ul7qqp)* status: 23 unresolved discussions, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[`LICENSE` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMbFAm-oOdUqLnR8Nd:-NSMbFAm-oOdUqLnR8Ne:bp3pe53) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/LICENSE#L1)):*
> ```
> Copyright (c) 2017-2023 by the drake-external-examples developers.
> ```

BTW consider clarifying that this is intended to be a copy of the MIT-0 license.
___
*[`drake_ament_cmake_installed/src/drake_ament_cmake_installed/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMbY_t-bAryb2Wc15p:-NSMbY_t-bAryb2Wc15q:b-z5xi56) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_ament_cmake_installed/src/drake_ament_cmake_installed/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW the first two non-copyright lines were also deleted here -- intentional?
___
*[`drake_ament_cmake_installed/src/drake_ament_cmake_installed/LICENSE` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMbjvqBdNyWuqsnhVc:-NSMbjvqBdNyWuqsnhVd:ba16qfc) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_ament_cmake_installed/src/drake_ament_cmake_installed/LICENSE#L1)):*
> ```
> Copyright (c) 2017-2023 by the drake-external-examples developers.
> ```

BTW consider noting that this is intended to be a copy of the MIT-0 license.
___
*[`drake_bazel_external/BUILD.bazel` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMbvIPD4gWg2Spy5g6:-NSMbvIPD4gWg2Spy5g7:bps46au) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_bazel_external/BUILD.bazel#L1)):*
> ```Starlark
> # SPDX-License-Identifier: MIT-0
> ```

BTW the first two  non-copyright lines got deleted -- intentional?
___
*[`drake_bazel_external/environ.bzl` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMc2PY7sherLZn9sPq:-NSMc2PY7sherLZn9sPr:bps46au) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_bazel_external/environ.bzl#L1)):*
> ```Starlark
> # SPDX-License-Identifier: MIT-0
> ```

BTW the first two  non-copyright lines got deleted -- intentional?
___
*[`drake_bazel_external/WORKSPACE` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMc41V54Rg-hlpKvjD:-NSMc41V54Rg-hlpKvjE:bps46au) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_bazel_external/WORKSPACE#L1)):*
> ```Starlark
> # SPDX-License-Identifier: MIT-0
> ```

BTW the first two  non-copyright lines got deleted -- intentional?
___
*[`drake_bazel_external/apps/BUILD.bazel` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMc7gP7m2tXuemj-RE:-NSMc7gP7m2tXuemj-RF:bps46au) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_bazel_external/apps/BUILD.bazel#L1)):*
> ```Starlark
> # SPDX-License-Identifier: MIT-0
> ```

BTW the first two  non-copyright lines got deleted -- intentional?
___
*[`drake_bazel_installed/BUILD.bazel` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMcIVR9JuHDPxlG_uL:-NSMcIVR9JuHDPxlG_uM:bps46au) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_bazel_installed/BUILD.bazel#L1)):*
> ```Starlark
> # SPDX-License-Identifier: MIT-0
> ```

BTW the first two  non-copyright lines got deleted -- intentional?
___
*[`drake_bazel_installed/WORKSPACE` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMcKfS0-Ryg-YA-4OF:-NSMcKfS0-Ryg-YA-4OG:bps46au) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_bazel_installed/WORKSPACE#L1)):*
> ```Starlark
> # SPDX-License-Identifier: MIT-0
> ```

BTW the first two  non-copyright lines got deleted -- intentional?
___
*[`drake_bazel_installed/apps/BUILD.bazel` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMcMWL6O1JyCDjReAz:-NSMcMWMAXvUTilG5bI8:bps46au) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_bazel_installed/apps/BUILD.bazel#L1)):*
> ```Starlark
> # SPDX-License-Identifier: MIT-0
> ```

BTW the first two  non-copyright lines got deleted -- intentional?
___
*[`drake_catkin_installed/src/drake_catkin_installed/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMcRw3A75Fod3wNyEO:-NSMcRw3A75Fod3wNyEP:bps46au) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_catkin_installed/src/drake_catkin_installed/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW the first two  non-copyright lines got deleted -- intentional?
___
*[`drake_catkin_installed/src/drake_catkin_installed/LICENSE` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMcV057eL0WoAp3z_T:-NSMcV057eL0WoAp3z_U:bn8iy06) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_catkin_installed/src/drake_catkin_installed/LICENSE#L1)):*
> ```
> Copyright (c) 2017-2023 by the drake-external-examples developers.
> ```

BTW consider noting that this is intended to be a copy of the MIT-0 license
___
*[`drake_cmake_external/drake_external_examples/apps/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMcjIXBRI7-nJATvQq:-NSMcjIXBRI7-nJATvQr:b3oumd3) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_cmake_external/drake_external_examples/apps/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW lost the first two non-copyright lines
___
*[`drake_cmake_installed/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMcpaX24t0vCHzbj_d:-NSMcpaX24t0vCHzbj_e:b3oumd3) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_cmake_installed/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW lost the first two non-copyright lines
___
*[`drake_cmake_installed/src/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMcrGnB18NZs4_frRo:-NSMcrGnB18NZs4_frRp:b3oumd3) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_cmake_installed/src/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW lost the first two non-copyright lines
___
*[`drake_cmake_installed/src/find_resource/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMctcQCa_pC1G-P1CK:-NSMctcQCa_pC1G-P1CL:b3oumd3) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_cmake_installed/src/find_resource/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW lost the first two non-copyright lines
___
*[`drake_cmake_installed/src/find_resource/find_resource_example.py` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMcxZl1IGB4kNE_38O:-NSMcxZl1IGB4kNE_38P:b3oumd3) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_cmake_installed/src/find_resource/find_resource_example.py#L1)):*
> ```Python
> # SPDX-License-Identifier: MIT-0
> ```

BTW lost the first two non-copyright lines
___
*[`drake_cmake_installed/src/particles/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMcysBAfmGnJvSpOML:-NSMcysBAfmGnJvSpOMM:b3oumd3) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_cmake_installed/src/particles/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW lost the first two non-copyright lines
___
*[`drake_cmake_installed/src/simple_bindings/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMd3rv4pJyFskqmJBk:-NSMd3rwD3Ur5U83JdQ1:b3oumd3) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW lost the first two non-copyright lines
___
*[`drake_cmake_installed/src/simple_continuous_time_system/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMd7-81k2hCd108Crn:-NSMd7-81k2hCd108Cro:b3oumd3) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_cmake_installed/src/simple_continuous_time_system/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW lost the first two non-copyright lines
___
*[`drake_cmake_installed/third_party/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMd9Gb3ZsMuZxHzgd7:-NSMd9Gb3ZsMuZxHzgd8:b3oumd3) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_cmake_installed/third_party/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW lost the first two non-copyright lines
___
*[`drake_cmake_installed_apt/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMdBLZCqqdaNoA8sR_:-NSMdBLZCqqdaNoA8sRa:b3oumd3) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_cmake_installed_apt/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW lost the first two non-copyright lines
___
*[`drake_cmake_installed_apt/src/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-NSMdCiW4GIAumdE3P-9:-NSMdCiW4GIAumdE3P-A:b3oumd3) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_cmake_installed_apt/src/CMakeLists.txt#L1)):*
> ```CMake
> # SPDX-License-Identifier: MIT-0
> ```

BTW lost the first two non-copyright lines

**Review by sherm1 — APPROVED** [review]
+@sherm1 for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/246#-:-NSMdnF8B0mKKM6RitOb:blr65vz)* status: 23 unresolved discussions, LGTM missing from assignee sherm1, platform LGTM missing (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/246)* status: 1 unresolved discussion, LGTM missing from assignee sherm1, platform LGTM missing (waiting on @sherm1)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/246#-NSMfFneAOE1G0phvg2i:-NSMfFneAOE1G0phvg2j:b-z601j5) (no related file):*
> SPDX is lovely! However the changes here seem contrary to the instructions here:
> > Therefore, you should not remove or modify existing copyright notices in files when adding an SPDX ID.

For someone who is contributing SPDX labels to a third-party repo they do not own, that would certainly be true.

Since we own this repo, we get to decide from first principles.  Do we want to annotate copyright ownership in every source file, or only in the top-level LICENSE file.  My vote was for the latter.

The alternative is that we say instead these two lines in every file:

```
# Copyright (c) 2017-2023 by the drake-external-examples developers.
# SPDX-License-Identifier: MIT-0
```

... and then perl pie the copyright year every January.  I didn't think that was valuable.  Unlike MIT or BSD-3-Clause, the users who copy our MIT-0 files from here into their own code are permitted to remove all of our comments and notices. For MIT-0 in particular, I don't think the copyright ownership is important.

WDYT?

___
___
*[`LICENSE` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/246#-NSMbFAm-oOdUqLnR8Nd:-NSMfKhGE0C78FArP0uz:bvx4s5o) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/LICENSE#L1)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider clarifying that this is intended to be a copy of the MIT-0 license.
</blockquote></details>

Adding that extra text to a LICENSE file would be contrary to approximately all other open source software on GitHub.
___
*[`drake_ament_cmake_installed/src/drake_ament_cmake_installed/CMakeLists.txt` line 1 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/246#-NSMbY_t-bAryb2Wc15p:-NSMfhksEyNPnN3R4v9W:bt9l97g) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/29cac5bb4ad2b925348baa4e36c709de654b9c85/drake_ament_cmake_installed/src/drake_ament_cmake_installed/CMakeLists.txt#L1)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW the first two non-copyright lines were also deleted here -- intentional?
</blockquote></details>

Done.  See new commit message.

**Review by sherm1 — APPROVED** [review]
Thanks for the discussion -- I am happy with this as is. :lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/246#-:-NSMwYJQB712ndmLbyyK:b-mbai33)* status: :shipit: complete! all discussions resolved, platform LGTM from [sherm1] (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/246#-NSMfFneAOE1G0phvg2i:-NSMw1z07W-X3OGi76dy:b-f4db9b) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> SPDX is lovely! However the changes here seem contrary to the instructions here:
> > Therefore, you should not remove or modify existing copyright notices in files when adding an SPDX ID.

For someone who is contributing SPDX labels to a third-party repo they do not own, that would certainly be true.

Since we own this repo, we get to decide from first principles.  Do we want to annotate copyright ownership in every source file, or only in the top-level LICENSE file.  My vote was for the latter.

The alternative is that we say instead these two lines in every file:

```
# Copyright (c) 2017-2023 by the drake-external-examples developers.
# SPDX-License-Identifier: MIT-0
```

... and then perl pie the copyright year every January.  I didn't think that was valuable.  Unlike MIT or BSD-3-Clause, the users who copy our MIT-0 files from here into their own code are permitted to remove all of our comments and notices. For MIT-0 in particular, I don't think the copyright ownership is important.

WDYT?
</blockquote></details>

I am happy to do without the copyright notices for examples.

___

**Comment by jwnimmer-tri** [comment]
Yay, and GitHub already noticed!

image

**Comment by cjds** [comment]
@sherm1 sorry for the late reply. Haven't been monitoring GitHub off late. Happy to contribute as well if applicable

**Comment by sherm1** [comment]
Thanks, Carl -- much appreciated. cc @jwnimmer-tri

**Pull request merged**
