### PR TITLE
Move and sync CPPLINT and LICENSE to examples

### PR DESCRIPTION
**Pull request by nicolecheetham**
Creates duplicates of CPPLINT and LICENSE for each of the drake examples in addition to syncing them.

https://github.com/RobotLocomotion/drake-external-examples/issues/309

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/318)

### CODE REVIEW

**Comment by nicolecheetham** [comment]
Is the location I chose for the CPPLINT.cfg and LICENSE files within the examples directories acceptable?

**Review by jwnimmer-tri — COMMENTED** [review]
Yes, the new homes are good.  One note below.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/318#-:-O7itR7s1s6HcA3nUdra:bn46plp)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @nicolecheetham)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/318#-O7it81m5-Q1EH7MoNce:-O7it81m5-Q1EH7MoNcf:bus7v0v) (no related file):*
nit One small tweak -- a copy of the LICENSE should also still remain in the root directory (it will cover the files that remain outside of the example directories, like `/README.md` and `/.github/**`).

(It's fine for CPPLINT.cfg to only live in the example subdirs as-is, since there is no C++ code outside of the example subdirs.)

___

**Review by nicolecheetham — COMMENTED** [review]
+@BetsyMcPhail for feature review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/318#-:-O7ivPedA67FBWwhkGVu:b-1dud86)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail and @jwnimmer-tri)

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 15 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/318#-:-O7ixSCR3EObiew8o8ss:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee betsymcphail, platform LGTM from [jwnimmer-tri] (waiting on @BetsyMcPhail and @nicolecheetham)

___
*[`private/test/file_sync_test.py` line 32 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/318#-O7ixN8d-Di6RcLwJ0hc:-O7ixN8d-Di6RcLwJ0hd:bbfkd16) ([raw file](https://github.com/RobotLocomotion/drake-external-examples/blob/d486f6f3d2897d7cdb73ff3d0d4613469a1b6b88/private/test/file_sync_test.py#L32)):*
> ```Python
>         "drake_cmake_installed_apt/CPPLINT.cfg",
>     ),
>     (
> ```

nit Mention the root here copy here as well.

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 14 of 16 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/318#-:-O7jA5N35xeT3krQeWQj:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [jwnimmer-tri, betsymcphail] (waiting on @nicolecheetham)

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/318)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri, betsymcphail] (waiting on @nicolecheetham)

**Pull request merged**
