### PR TITLE
Move mac prereqs to drake_cmake_installed

### PR DESCRIPTION
**Pull request by nicolecheetham**
MacOS supports the drake_cmake_installed example. Therefore, this moves the mac installation files to this example.

Issue: https://github.com/RobotLocomotion/drake-external-examples/issues/309

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315)

### CODE REVIEW

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315#-:-O7VcORv3aQqXSaEHgE3:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
+@rpoyner-tri for platform review please

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315#-:-O7ZbH-H0vX0z6NMTDTW:b-hnc6mz)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM from [betsymcphail] (waiting on @rpoyner-tri)

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315#-:-O7ZcpitExjR3vkX0rOS:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @nicolecheetham)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315#-O7Zcq6G5i3H1W_ZMt8i:-O7Zcq6G5i3H1W_ZMt8j:b-bbz9nk) (no related file):*
nit Which examples are supported for macOS, and what documentation says so, and explains how to use it? It's not clear from this PR, and it looks unclear to me on main as well. I don't necessarily need to block this patch, but the doc for macos needs to be more clear.

___

**Review by rpoyner-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @nicolecheetham)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315#-O7Zcq6G5i3H1W_ZMt8i:-O7ZdiTD20qiW30TRUV8:bxkuo3i) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit Which examples are supported for macOS, and what documentation says so, and explains how to use it? It's not clear from this PR, and it looks unclear to me on main as well. I don't necessarily need to block this patch, but the doc for macos needs to be more clear.
</blockquote></details>

So, `.github/workflows/.ci.yml` gives some clues, but that's hardly the first place a casual user would start to look.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315#-O7Zcq6G5i3H1W_ZMt8i:-O7ZeE5S-EvgDlyMO4ce:b-fdg9oe) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

So, `.github/workflows/.ci.yml` gives some clues, but that's hardly the first place a casual user would start to look.
</blockquote></details>

All of the (non-ROS) examples are _supported_ on macOS, but only some of them are _tested_ on macOS.  The documentation we are missing is the top-level README changing "Not all example projects are supported on macOS" to "The Ament and Catkin projects are supported on macOS".

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315#-O7Zcq6G5i3H1W_ZMt8i:-O7Zea8103IZPqK-1WWr:b-m396wr) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

All of the (non-ROS) examples are _supported_ on macOS, but only some of them are _tested_ on macOS.  The documentation we are missing is the top-level README changing "Not all example projects are supported on macOS" to "The Ament and Catkin projects are supported on macOS".
</blockquote></details>

Gllrgh, I missed a not:

The Ament and Catkin projects are NOT supported on macOS

___

**Review by rpoyner-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @nicolecheetham)

**Review by rpoyner-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @nicolecheetham)

**Review by BetsyMcPhail — COMMENTED** [review]
Per f2f conversation, Nicole is going to update this PR to add a setup/ or tools/ or similar directory above the mac/ subdirectory. This is looking ahead to eventually adding a ubuntu/ subdirectory as well

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315#-:-O7dbQiJD7ICD2YkwYwS:b-81olai)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @nicolecheetham)

**Review by BetsyMcPhail — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/315#-:-O7det_h8EiQ30UcwZT0:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, rpoyner-tri] (waiting on @rpoyner-tri)

**Pull request merged**
