### PR TITLE
Refactor Jenkins build tests

### PR DESCRIPTION
**Pull request by nicolecheetham**
Cleans up Jenkins build tests workflow making it more clear and concise

Additionally, removes build tests in the Jenkins that already exist as GHA build tests
* Jeremy could not remember why there was redundancy of build tests in the Jenkinsfile and therefore advised removing the build tests which duplicate the ones in the GHA: drake_bazel_download, drake_catkin_installed, drake_cmake_installed

Issue: https://github.com/RobotLocomotion/drake-external-examples/issues/61

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300)

### CODE REVIEW

**Review by nicolecheetham — COMMENTED** [review]
+@BetsyMcPhail for feature review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300#-:-O6abDVu3VTWRVY2d_3K:bj8rs74)* status: all discussions resolved, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300)* status: 1 unresolved discussion, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @nicolecheetham)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300#-O6g2MYkDfD1OkLHV7YF):*
BTW As this PR is actually making a functional change by removing some tests from Jenkins, it would be good to explicitly mention that here. That would make it clear that they aren't being removed by accident.

Related, the "Continuous Integration" section of README.md needs to be updated to account for these removals.

**Review by nicolecheetham — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300)* status: 1 unresolved discussion, LGTM missing from assignee betsymcphail, platform LGTM missing (waiting on @BetsyMcPhail)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300#-O6g2MYkDfD1OkLHV7YF):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

BTW As this PR is actually making a functional change by removing some tests from Jenkins, it would be good to explicitly mention that here. That would make it clear that they aren't being removed by accident.

Related, the "Continuous Integration" section of README.md needs to be updated to account for these removals.
</blockquote></details>

Thank you for pointing this out. I have updated the description of the PR to mention the functional change as well as the README.md

**Review by BetsyMcPhail — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300#-:-O6vYgtA1H3vq1URMBsM:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail] (waiting on @nicolecheetham)

**Review by nicolecheetham — COMMENTED** [review]
+@jwnimmer-tri for platform review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300#-:-O6vgvx04jw3XWUe262d:b-ykw85)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM from [betsymcphail] (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300#-:-O6w8hfvBnmkZfYbOA1a:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, jwnimmer-tri] (waiting on @nicolecheetham)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300#-O6w8ZtvAEQDv7OvYLkn):*
When this merges, we need a much better summary -- either with a force-push to adjust the commit message, or edit it during the squash-and-merge using the web interface.

The verb "refactor" indicates a cleanup with no change in functionality, but here we have two important changes in functionality:

(1) Remove three build flavors from Jenkins because they are redundant with GHA:
* drake_bazel_download
* drake_catkin_installed
* drake_cmake_installed

(2) In the remaining two build flavors in Jenkins, run each on a separate machine, so their setup script and/or results do not contaminate each other.

**Review by BetsyMcPhail — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, jwnimmer-tri] (waiting on @jwnimmer-tri)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300#-O6w8ZtvAEQDv7OvYLkn):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When this merges, we need a much better summary -- either with a force-push to adjust the commit message, or edit it during the squash-and-merge using the web interface.

The verb "refactor" indicates a cleanup with no change in functionality, but here we have two important changes in functionality:

(1) Remove three build flavors from Jenkins because they are redundant with GHA:
* drake_bazel_download
* drake_catkin_installed
* drake_cmake_installed

(2) In the remaining two build flavors in Jenkins, run each on a separate machine, so their setup script and/or results do not contaminate each other.
</blockquote></details>

I don't believe 2) was implemented in this PR... I'm not sure if that was intentional or not? Nicole, I'm happy to take the Jenkins refactor (splitting into two jobs) as a follow-up to this PR if you would like.

**Review by jwnimmer-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, jwnimmer-tri] (waiting on @BetsyMcPhail)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300#-O6w8ZtvAEQDv7OvYLkn):*
<details><summary><i>Previously, BetsyMcPhail (Betsy McPhail) wrote…</i></summary><blockquote>

I don't believe 2) was implemented in this PR... I'm not sure if that was intentional or not? Nicole, I'm happy to take the Jenkins refactor (splitting into two jobs) as a follow-up to this PR if you would like.
</blockquote></details>

Ah, you're right.  I misread the groovy.

In the case it's just (1) as the only functional change.

I would also be OK to mention something like "refactor code to remove layers of confusing indirection" in the commit message, if you like.

**Review by nicolecheetham — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, jwnimmer-tri] (waiting on @BetsyMcPhail and @jwnimmer-tri)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300#-O6w8ZtvAEQDv7OvYLkn):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Ah, you're right.  I misread the groovy.

In the case it's just (1) as the only functional change.

I would also be OK to mention something like "refactor code to remove layers of confusing indirection" in the commit message, if you like.
</blockquote></details>

Sure. Splitting the two jobs to run on a separate machine can be a follow-up to this PR once this one is merged

And I'll see if I can include both the build refactoring and the removal of the redundant build flavors into a commit message. If not, I can more closely use your suggestion.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, jwnimmer-tri] (waiting on @BetsyMcPhail)

**Review by BetsyMcPhail — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, jwnimmer-tri] (waiting on @nicolecheetham)

**Review by BetsyMcPhail — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300)* status: 1 unresolved discussion, platform LGTM from [betsymcphail, jwnimmer-tri] (waiting on @jwnimmer-tri and @nicolecheetham)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300#-O6w8ZtvAEQDv7OvYLkn):*
<details><summary><i>Previously, nicolecheetham (Nicole C.) wrote…</i></summary><blockquote>

Sure. Splitting the two jobs to run on a separate machine can be a follow-up to this PR once this one is merged

And I'll see if I can include both the build refactoring and the removal of the redundant build flavors into a commit message. If not, I can more closely use your suggestion.
</blockquote></details>

Follow-up issue: https://github.com/RobotLocomotion/drake-external-examples/issues/303

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-external-examples/300)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [betsymcphail, jwnimmer-tri] (waiting on @nicolecheetham)

**Pull request merged**
