### PR TITLE
[drake_cmake_installed] CMakeLists uses drake_PYTHON_VERSION

### PR DESCRIPTION
**Pull request by adeeb10abbas**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244)

### CODE REVIEW

**Comment by adeeb10abbas** [comment]
@jwnimmer-tri for review/discussion, please!

**Review by jwnimmer-tri — CHANGES_REQUESTED** [review]
+@svenevs for feature review, please.

+@jwnimmer-tri for platform review.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244#-:-NGUOZRd45sROUEsNZ9o:bol7n7p)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee svenevs, platform LGTM missing (waiting on @adeeb10abbas and @svenevs)

___
*[`drake_cmake_installed/CMakeLists.txt` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244#-NGUOLug-MnXBa79FmzK:-NGUOLug-MnXBa79FmzL:b-ngeu4s) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/facfca03be7604239c052d914c27b5fd03dc90b1/drake_cmake_installed/CMakeLists.txt#L41)):*
> ```CMake
> 
> include(CTest)
> set(FIND_PYTHON_INTERP_VERSION ${drake_PYTHON_VERSION})
> ```

I belatedly realized that `drake_PYTHON_VERSION` will probably be undefined until after we call `find_package(drake CONFIG REQUIRED)`?

So the "find drake" will need to move up higher in this file, it seems to me?
___
*[`drake_cmake_installed/CMakeLists.txt` line 56 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244#-NGUOf_W9V_7qXtDbK5V:-NGUOf_W9V_7qXtDbK5W:b-ysmk80) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/facfca03be7604239c052d914c27b5fd03dc90b1/drake_cmake_installed/CMakeLists.txt#L56)):*
> ```CMake
> find_package(PythonLibs ${FIND_PYTHON_INTERP_VERSION} MODULE REQUIRED)
> 
> find_package(drake CONFIG REQUIRED)
> ```

I think _this_ is what sets `drake_PYTHON_VERSION`.

**Review by adeeb10abbas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee svenevs, platform LGTM missing (waiting on @jwnimmer-tri and @svenevs)

___
*[`drake_cmake_installed/CMakeLists.txt` line 56 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244#-NGUOf_W9V_7qXtDbK5V:-NGUPmq71n3rjIeu8y1V:b-curk2k) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/facfca03be7604239c052d914c27b5fd03dc90b1/drake_cmake_installed/CMakeLists.txt#L56)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think _this_ is what sets `drake_PYTHON_VERSION`.
</blockquote></details>

yes, I think you're correct. I must've missed it. Will fix it and push it now

**Review by adeeb10abbas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee svenevs, platform LGTM missing (waiting on @jwnimmer-tri and @svenevs)

___
*[`drake_cmake_installed/CMakeLists.txt` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244#-NGUOLug-MnXBa79FmzK:-NGWWJ7N9XAOaAcoXN5E:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/facfca03be7604239c052d914c27b5fd03dc90b1/drake_cmake_installed/CMakeLists.txt#L41)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I belatedly realized that `drake_PYTHON_VERSION` will probably be undefined until after we call `find_package(drake CONFIG REQUIRED)`?

So the "find drake" will need to move up higher in this file, it seems to me?
</blockquote></details>

Done.

**Review by svenevs — COMMENTED** [review]
:lgtm: with small cleanup suggestion.  I've got a script that tests the jammy and focal `.tar.gz` and it works as expected for this machine.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244#-:-NGWuKgNAB_7LKPiOu6L:b-rjw1co)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[`drake_cmake_installed/CMakeLists.txt` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244#-NGUOLug-MnXBa79FmzK:-NGWtfTF0Kcitw30KGxg:bd4qilp) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/facfca03be7604239c052d914c27b5fd03dc90b1/drake_cmake_installed/CMakeLists.txt#L41)):*
> I belatedly realized that drake_PYTHON_VERSION will probably be undefined until after we call find_package(drake CONFIG REQUIRED)?

Correct, `find_package( <thing> CONFIG)` essentially runs `thing-config.cmake` in the "same scope" so that variables can be set by the config package.

There's no need to keep the `FIND_PYTHON_INTERP_VERSION` variable, suggestion:

```diff
diff --git a/drake_cmake_installed/CMakeLists.txt b/drake_cmake_installed/CMakeLists.txt
index 953553e..57a1085 100644
--- a/drake_cmake_installed/CMakeLists.txt
+++ b/drake_cmake_installed/CMakeLists.txt
@@ -41,8 +41,7 @@ include(CTest)
 
 find_package(drake CONFIG REQUIRED)
 
-set(FIND_PYTHON_INTERP_VERSION ${drake_PYTHON_VERSION})
-find_package(PythonInterp ${FIND_PYTHON_INTERP_VERSION} MODULE REQUIRED EXACT)
+find_package(PythonInterp ${drake_PYTHON_VERSION} MODULE REQUIRED EXACT)
 
 find_program(PYTHON_EXECUTABLE NAMES python3
   PATHS "${FIND_PYTHON_EXECUTABLE_PATHS}"
@@ -54,7 +53,7 @@ execute_process(COMMAND ${PYTHON_EXECUTABLE}-config --exec-prefix
   OUTPUT_STRIP_TRAILING_WHITESPACE
 )
 list(APPEND CMAKE_PREFIX_PATH "${PYTHON_EXEC_PREFIX}")
-find_package(PythonLibs ${FIND_PYTHON_INTERP_VERSION} MODULE REQUIRED)
+find_package(PythonLibs ${drake_PYTHON_VERSION} MODULE REQUIRED)
 
 get_filename_component(PYTHONPATH
   "${drake_DIR}/../../python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/site-packages"
```

**Review by svenevs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[`drake_cmake_installed/CMakeLists.txt` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244#-NGUOLug-MnXBa79FmzK:-NGWvaqz6XEvIoqaNz3O:b-lgteol) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/facfca03be7604239c052d914c27b5fd03dc90b1/drake_cmake_installed/CMakeLists.txt#L41)):*
<details><summary><i>Previously, svenevs (Stephen McDowell) wrote…</i></summary><blockquote>

> I belatedly realized that drake_PYTHON_VERSION will probably be undefined until after we call find_package(drake CONFIG REQUIRED)?

Correct, `find_package( <thing> CONFIG)` essentially runs `thing-config.cmake` in the "same scope" so that variables can be set by the config package.

There's no need to keep the `FIND_PYTHON_INTERP_VERSION` variable, suggestion:

```diff
diff --git a/drake_cmake_installed/CMakeLists.txt b/drake_cmake_installed/CMakeLists.txt
index 953553e..57a1085 100644
--- a/drake_cmake_installed/CMakeLists.txt
+++ b/drake_cmake_installed/CMakeLists.txt
@@ -41,8 +41,7 @@ include(CTest)
 
 find_package(drake CONFIG REQUIRED)
 
-set(FIND_PYTHON_INTERP_VERSION ${drake_PYTHON_VERSION})
-find_package(PythonInterp ${FIND_PYTHON_INTERP_VERSION} MODULE REQUIRED EXACT)
+find_package(PythonInterp ${drake_PYTHON_VERSION} MODULE REQUIRED EXACT)
 
 find_program(PYTHON_EXECUTABLE NAMES python3
   PATHS "${FIND_PYTHON_EXECUTABLE_PATHS}"
@@ -54,7 +53,7 @@ execute_process(COMMAND ${PYTHON_EXECUTABLE}-config --exec-prefix
   OUTPUT_STRIP_TRAILING_WHITESPACE
 )
 list(APPEND CMAKE_PREFIX_PATH "${PYTHON_EXEC_PREFIX}")
-find_package(PythonLibs ${FIND_PYTHON_INTERP_VERSION} MODULE REQUIRED)
+find_package(PythonLibs ${drake_PYTHON_VERSION} MODULE REQUIRED)
 
 get_filename_component(PYTHONPATH
   "${drake_DIR}/../../python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/site-packages"
```
</blockquote></details>

Actually, sorry, small oversight -- the `find_package` for `PythonLibs` should also add `EXACT` here, IIRC the original issue was that mysteriously some newer python versions appeared in the GitHub Actions environment.

**Review by jwnimmer-tri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @adeeb10abbas)

___
*[`drake_cmake_installed/CMakeLists.txt` line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244#-NGX9i8a6lFBE_toVZaA:-NGX9i8a6lFBE_toVZaB:b-8iscmq) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/e5ac633c0a9dd38eae354bdf357cbcfc8f13f6f8/drake_cmake_installed/CMakeLists.txt#L57)):*
(I'm moving the other discussion down here where it applies, so I can close the other thread...)

> Actually, sorry, small oversight -- the find_package for PythonLibs should also add EXACT here, IIRC the original issue was that mysteriously some newer python versions appeared in the GitHub Actions environment.

**Review by adeeb10abbas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[`drake_cmake_installed/CMakeLists.txt` line 57 at r2](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244#-NGX9i8a6lFBE_toVZaA:-NGZJfib-1F9k8AWMTQM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-external-examples/blob/e5ac633c0a9dd38eae354bdf357cbcfc8f13f6f8/drake_cmake_installed/CMakeLists.txt#L57)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

(I'm moving the other discussion down here where it applies, so I can close the other thread...)

> Actually, sorry, small oversight -- the find_package for PythonLibs should also add EXACT here, IIRC the original issue was that mysteriously some newer python versions appeared in the GitHub Actions environment.

</blockquote></details>

Done.

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-external-examples/244#-:-NGZq8dl5LcqDrBFf5eB:bnfp4nl)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @adeeb10abbas)

**Pull request merged**
